"""add_location_sharing_table

Revision ID: 0763d2f84510
Revises: 658d9ba25f3d
Create Date: 2025-09-23 09:36:20.446907

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0763d2f84510"
down_revision: Union[str, Sequence[str], None] = "658d9ba25f3d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Create locationsharing table
    op.create_table(
        "locationsharing",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("trip_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("share_code", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["trip_id"], ["trips.id"]),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("share_code"),
    )

    # Create indexes for locationsharing table
    op.create_index(
        op.f("ix_locationsharing_id"), "locationsharing", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_locationsharing_trip_id"), "locationsharing", ["trip_id"], unique=False
    )
    op.create_index(
        op.f("ix_locationsharing_user_id"), "locationsharing", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_locationsharing_share_code"),
        "locationsharing",
        ["share_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_locationsharing_is_active"),
        "locationsharing",
        ["is_active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_locationsharing_expires_at"),
        "locationsharing",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_locationsharing_created_at"),
        "locationsharing",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_locationsharing_updated_at"),
        "locationsharing",
        ["updated_at"],
        unique=False,
    )

    # Create other spatial indexes
    op.create_index(
        op.f("ix_accommodations_location"), "accommodations", ["location"], unique=False
    )
    op.create_index(
        op.f("ix_location_histories_location"),
        "location_histories",
        ["location"],
        unique=False,
    )
    op.create_index(
        op.f("ix_offline_activities_location"),
        "offline_activities",
        ["location"],
        unique=False,
    )
    op.create_index(
        op.f("ix_offline_activity_route_data_route"),
        "offline_activity_route_data",
        ["route"],
        unique=False,
    )
    op.create_index(
        op.f("ix_online_activities_location"),
        "online_activities",
        ["location"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop spatial indexes
    op.drop_index(op.f("ix_online_activities_location"), table_name="online_activities")
    op.drop_index(
        op.f("ix_offline_activity_route_data_route"),
        table_name="offline_activity_route_data",
    )
    op.drop_index(
        op.f("ix_offline_activities_location"), table_name="offline_activities"
    )
    op.drop_index(
        op.f("ix_location_histories_location"), table_name="location_histories"
    )
    op.drop_index(op.f("ix_accommodations_location"), table_name="accommodations")

    # Drop locationsharing indexes and table
    op.drop_index(op.f("ix_locationsharing_updated_at"), table_name="locationsharing")
    op.drop_index(op.f("ix_locationsharing_created_at"), table_name="locationsharing")
    op.drop_index(op.f("ix_locationsharing_expires_at"), table_name="locationsharing")
    op.drop_index(op.f("ix_locationsharing_is_active"), table_name="locationsharing")
    op.drop_index(op.f("ix_locationsharing_share_code"), table_name="locationsharing")
    op.drop_index(op.f("ix_locationsharing_user_id"), table_name="locationsharing")
    op.drop_index(op.f("ix_locationsharing_trip_id"), table_name="locationsharing")
    op.drop_index(op.f("ix_locationsharing_id"), table_name="locationsharing")
    op.drop_table("locationsharing")
    # ### end Alembic commands ###
