"""move_tourist_id_to_trips_nullable

Revision ID: 2a1c6ed4a3f2
Revises: 74167a091164
Create Date: 2025-09-17 05:18:46.921861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2a1c6ed4a3f2'
down_revision: Union[str, Sequence[str], None] = '74167a091164'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spatial_ref_sys')
    op.drop_index(op.f('idx_trek_routes_route'), table_name='trek_routes', postgresql_using='gist')
    op.drop_index(op.f('ix_trek_routes_created_at'), table_name='trek_routes')
    op.drop_index(op.f('ix_trek_routes_id'), table_name='trek_routes')
    op.drop_index(op.f('ix_trek_routes_trek_id'), table_name='trek_routes')
    op.drop_index(op.f('ix_trek_routes_updated_at'), table_name='trek_routes')
    op.drop_table('trek_routes')
    op.add_column('accommodations', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('accommodations', sa.Column('longitude', sa.Float(), nullable=True))
    op.drop_index(op.f('idx_accommodations_location'), table_name='accommodations', postgresql_using='gist')
    op.drop_index(op.f('ix_accommodations_location'), table_name='accommodations')
    op.create_index(op.f('ix_accommodations_latitude'), 'accommodations', ['latitude'], unique=False)
    op.create_index(op.f('ix_accommodations_longitude'), 'accommodations', ['longitude'], unique=False)
    op.drop_column('accommodations', 'location')
    op.add_column('places', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('places', sa.Column('longitude', sa.Float(), nullable=True))
    op.create_index(op.f('ix_places_latitude'), 'places', ['latitude'], unique=False)
    op.create_index(op.f('ix_places_longitude'), 'places', ['longitude'], unique=False)
    op.add_column('tracking_devices', sa.Column('last_latitude', sa.Float(), nullable=True))
    op.add_column('tracking_devices', sa.Column('last_longitude', sa.Float(), nullable=True))
    op.drop_index(op.f('idx_tracking_devices_last_known_location'), table_name='tracking_devices', postgresql_using='gist')
    op.drop_index(op.f('ix_tracking_devices_last_known_location'), table_name='tracking_devices')
    op.create_index(op.f('ix_tracking_devices_last_latitude'), 'tracking_devices', ['last_latitude'], unique=False)
    op.create_index(op.f('ix_tracking_devices_last_longitude'), 'tracking_devices', ['last_longitude'], unique=False)
    op.drop_column('tracking_devices', 'last_known_location')
    op.add_column('treks', sa.Column('district', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('treks', sa.Column('minimum_people', sa.Integer(), nullable=True))
    op.add_column('treks', sa.Column('maximum_people', sa.Integer(), nullable=True))
    op.add_column('treks', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.drop_index(op.f('ix_treks_cost_per_person'), table_name='treks')
    op.drop_index(op.f('ix_treks_guide_required'), table_name='treks')
    op.drop_index(op.f('ix_treks_maximum_age'), table_name='treks')
    op.drop_index(op.f('ix_treks_minimum_age'), table_name='treks')
    op.drop_index(op.f('ix_treks_nearest_town'), table_name='treks')
    op.create_index(op.f('ix_treks_district'), 'treks', ['district'], unique=False)
    op.create_index(op.f('ix_treks_updated_at'), 'treks', ['updated_at'], unique=False)
    op.add_column('trips', sa.Column('itinerary_id', sa.Integer(), nullable=False))
    op.add_column('trips', sa.Column('tourist_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('trips', 'blockchain_transaction_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_trips_blockchain_id'), table_name='trips')
    op.create_index(op.f('ix_trips_itinerary_id'), 'trips', ['itinerary_id'], unique=False)
    op.create_index(op.f('ix_trips_tourist_id'), 'trips', ['tourist_id'], unique=False)
    op.create_foreign_key(None, 'trips', 'itineraries', ['itinerary_id'], ['id'])
    op.drop_column('trips', 'blockchain_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('blockchain_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'trips', type_='foreignkey')
    op.drop_index(op.f('ix_trips_tourist_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_itinerary_id'), table_name='trips')
    op.create_index(op.f('ix_trips_blockchain_id'), 'trips', ['blockchain_id'], unique=False)
    op.alter_column('trips', 'blockchain_transaction_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('trips', 'tourist_id')
    op.drop_column('trips', 'itinerary_id')
    op.drop_index(op.f('ix_treks_updated_at'), table_name='treks')
    op.drop_index(op.f('ix_treks_district'), table_name='treks')
    op.create_index(op.f('ix_treks_nearest_town'), 'treks', ['nearest_town'], unique=False)
    op.create_index(op.f('ix_treks_minimum_age'), 'treks', ['minimum_age'], unique=False)
    op.create_index(op.f('ix_treks_maximum_age'), 'treks', ['maximum_age'], unique=False)
    op.create_index(op.f('ix_treks_guide_required'), 'treks', ['guide_required'], unique=False)
    op.create_index(op.f('ix_treks_cost_per_person'), 'treks', ['cost_per_person'], unique=False)
    op.drop_column('treks', 'updated_at')
    op.drop_column('treks', 'maximum_people')
    op.drop_column('treks', 'minimum_people')
    op.drop_column('treks', 'district')
    op.add_column('tracking_devices', sa.Column('last_known_location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_tracking_devices_last_longitude'), table_name='tracking_devices')
    op.drop_index(op.f('ix_tracking_devices_last_latitude'), table_name='tracking_devices')
    op.create_index(op.f('ix_tracking_devices_last_known_location'), 'tracking_devices', ['last_known_location'], unique=False)
    op.create_index(op.f('idx_tracking_devices_last_known_location'), 'tracking_devices', ['last_known_location'], unique=False, postgresql_using='gist')
    op.drop_column('tracking_devices', 'last_longitude')
    op.drop_column('tracking_devices', 'last_latitude')
    op.drop_index(op.f('ix_places_longitude'), table_name='places')
    op.drop_index(op.f('ix_places_latitude'), table_name='places')
    op.drop_column('places', 'longitude')
    op.drop_column('places', 'latitude')
    op.add_column('accommodations', sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_accommodations_longitude'), table_name='accommodations')
    op.drop_index(op.f('ix_accommodations_latitude'), table_name='accommodations')
    op.create_index(op.f('ix_accommodations_location'), 'accommodations', ['location'], unique=False)
    op.create_index(op.f('idx_accommodations_location'), 'accommodations', ['location'], unique=False, postgresql_using='gist')
    op.drop_column('accommodations', 'longitude')
    op.drop_column('accommodations', 'latitude')
    op.create_table('trek_routes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('trek_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('route', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['trek_id'], ['treks.id'], name=op.f('trek_routes_trek_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('trek_routes_pkey'))
    )
    op.create_index(op.f('ix_trek_routes_updated_at'), 'trek_routes', ['updated_at'], unique=False)
    op.create_index(op.f('ix_trek_routes_trek_id'), 'trek_routes', ['trek_id'], unique=False)
    op.create_index(op.f('ix_trek_routes_id'), 'trek_routes', ['id'], unique=False)
    op.create_index(op.f('ix_trek_routes_created_at'), 'trek_routes', ['created_at'], unique=False)
    op.create_index(op.f('idx_trek_routes_route'), 'trek_routes', ['route'], unique=False, postgresql_using='gist')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    # ### end Alembic commands ###
