"""add_alerts_table

Revision ID: 480ca0bdc4b0
Revises: 0763d2f84510
Create Date: 2025-09-23 21:50:09.222432

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "480ca0bdc4b0"
down_revision: Union[str, Sequence[str], None] = "0763d2f84510"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_accommodations_location"), "accommodations", ["location"], unique=False
    )
    op.create_index(
        op.f("ix_location_histories_location"),
        "location_histories",
        ["location"],
        unique=False,
    )
    op.create_index(
        op.f("ix_offline_activities_location"),
        "offline_activities",
        ["location"],
        unique=False,
    )
    op.create_index(
        op.f("ix_offline_activity_route_data_route"),
        "offline_activity_route_data",
        ["route"],
        unique=False,
    )
    op.create_index(
        op.f("ix_online_activities_location"),
        "online_activities",
        ["location"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_online_activities_location"), table_name="online_activities")
    op.drop_index(
        op.f("ix_offline_activity_route_data_route"),
        table_name="offline_activity_route_data",
    )
    op.drop_index(
        op.f("ix_offline_activities_location"), table_name="offline_activities"
    )
    op.drop_index(
        op.f("ix_location_histories_location"), table_name="location_histories"
    )
    op.drop_index(op.f("ix_accommodations_location"), table_name="accommodations")
    # ### end Alembic commands ###
