"""add_alerts_table

Revision ID: 480ca0bdc4b0
Revises: 0763d2f84510
Create Date: 2025-09-23 21:50:09.222432

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "480ca0bdc4b0"
down_revision: Union[str, Sequence[str], None] = "0763d2f84510"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create indexes with IF NOT EXISTS to avoid conflicts in production
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_accommodations_location ON accommodations USING GIST (location)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_location_histories_location ON location_histories USING GIST (location)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_offline_activities_location ON offline_activities USING GIST (location)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_offline_activity_route_data_route ON offline_activity_route_data USING GIST (route)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_online_activities_location ON online_activities USING GIST (location)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop indexes with IF EXISTS to avoid errors if they don't exist
    op.execute("DROP INDEX IF EXISTS ix_online_activities_location")
    op.execute("DROP INDEX IF EXISTS ix_offline_activity_route_data_route")
    op.execute("DROP INDEX IF EXISTS ix_offline_activities_location")
    op.execute("DROP INDEX IF EXISTS ix_location_histories_location")
    op.execute("DROP INDEX IF EXISTS ix_accommodations_location")
    # ### end Alembic commands ###
