"""add_places_table_and_update_itinerary_structure

Revision ID: 4ac136f61ee6
Revises: dae22fdf0f44
Create Date: 2025-09-09 19:36:34.000706

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "4ac136f61ee6"
down_revision: Union[str, Sequence[str], None] = "dae22fdf0f44"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Create places table first
    op.create_table(
        "places",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "place_type",
            sa.Enum(
                "TREK",
                "CITY_TOUR",
                "TEMPLE",
                "HISTORICAL_SITE",
                "NATURE_SPOT",
                "ADVENTURE_PARK",
                "MUSEUM",
                "MARKET",
                "BEACH",
                "HILL_STATION",
                "WATERFALL",
                "WILDLIFE_SANCTUARY",
                "OTHER",
                name="placetypeenum",
            ),
            nullable=False,
        ),
        sa.Column("city", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("state", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("country", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column(
            "difficulty_level",
            sa.Enum(
                "EASY", "MODERATE", "DIFFICULT", "EXTREME", name="difficultylevelenum"
            ),
            nullable=False,
        ),
        sa.Column("estimated_duration_hours", sa.Float(), nullable=True),
        sa.Column(
            "best_time_to_visit", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("entry_fee", sa.Float(), nullable=True),
        sa.Column("safety_rating", sa.Integer(), nullable=False),
        sa.Column("accessibility_rating", sa.Integer(), nullable=False),
        sa.Column(
            "facilities_available", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("contact_info", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("opening_hours", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "special_instructions", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_places_city"), "places", ["city"], unique=False)
    op.create_index(op.f("ix_places_country"), "places", ["country"], unique=False)
    op.create_index(
        op.f("ix_places_created_at"), "places", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_places_difficulty_level"), "places", ["difficulty_level"], unique=False
    )
    op.create_index(op.f("ix_places_id"), "places", ["id"], unique=False)
    op.create_index(op.f("ix_places_name"), "places", ["name"], unique=False)
    op.create_index(
        op.f("ix_places_place_type"), "places", ["place_type"], unique=False
    )
    op.create_index(
        op.f("ix_places_safety_rating"), "places", ["safety_rating"], unique=False
    )
    op.create_index(op.f("ix_places_state"), "places", ["state"], unique=False)
    op.create_index(
        op.f("ix_places_updated_at"), "places", ["updated_at"], unique=False
    )

    # Skip dropping spatial_ref_sys - it's a PostGIS system table
    # op.drop_table('spatial_ref_sys')

    op.add_column(
        "itineraries",
        sa.Column(
            "itinerary_type",
            sa.Enum("TREK", "CITY_TOUR", "MIXED", name="itinerarytypeenum"),
            nullable=False,
        ),
    )
    op.add_column(
        "itineraries", sa.Column("primary_place_id", sa.Integer(), nullable=True)
    )
    op.add_column(
        "itineraries",
        sa.Column(
            "destination_city", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
    )
    op.add_column(
        "itineraries",
        sa.Column(
            "destination_state", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
    )
    op.add_column(
        "itineraries",
        sa.Column(
            "destination_country", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
    )
    op.create_index(
        op.f("ix_itineraries_destination_city"),
        "itineraries",
        ["destination_city"],
        unique=False,
    )
    op.create_index(
        op.f("ix_itineraries_destination_country"),
        "itineraries",
        ["destination_country"],
        unique=False,
    )
    op.create_index(
        op.f("ix_itineraries_destination_state"),
        "itineraries",
        ["destination_state"],
        unique=False,
    )
    op.create_index(
        op.f("ix_itineraries_itinerary_type"),
        "itineraries",
        ["itinerary_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_itineraries_primary_place_id"),
        "itineraries",
        ["primary_place_id"],
        unique=False,
    )
    op.create_foreign_key(None, "itineraries", "places", ["primary_place_id"], ["id"])
    op.drop_column("itineraries", "submitted_at")
    op.add_column(
        "itinerary_days",
        sa.Column(
            "day_type",
            sa.Enum("TREK_DAY", "PLACE_VISIT_DAY", name="daytypeenum"),
            nullable=False,
        ),
    )
    op.add_column("itinerary_days", sa.Column("trek_id", sa.Integer(), nullable=True))
    op.add_column(
        "itinerary_days", sa.Column("primary_place_id", sa.Integer(), nullable=True)
    )
    op.add_column(
        "itinerary_days", sa.Column("accommodation_latitude", sa.Float(), nullable=True)
    )
    op.add_column(
        "itinerary_days",
        sa.Column("accommodation_longitude", sa.Float(), nullable=True),
    )
    op.create_index(
        op.f("ix_itinerary_days_day_type"), "itinerary_days", ["day_type"], unique=False
    )
    op.create_index(
        op.f("ix_itinerary_days_primary_place_id"),
        "itinerary_days",
        ["primary_place_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_itinerary_days_trek_id"), "itinerary_days", ["trek_id"], unique=False
    )
    op.create_foreign_key(
        None, "itinerary_days", "places", ["primary_place_id"], ["id"]
    )
    op.create_foreign_key(None, "itinerary_days", "treks", ["trek_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "itinerary_days", type_="foreignkey")
    op.drop_constraint(None, "itinerary_days", type_="foreignkey")
    op.drop_index(op.f("ix_itinerary_days_trek_id"), table_name="itinerary_days")
    op.drop_index(
        op.f("ix_itinerary_days_primary_place_id"), table_name="itinerary_days"
    )
    op.drop_index(op.f("ix_itinerary_days_day_type"), table_name="itinerary_days")
    op.drop_column("itinerary_days", "accommodation_longitude")
    op.drop_column("itinerary_days", "accommodation_latitude")
    op.drop_column("itinerary_days", "primary_place_id")
    op.drop_column("itinerary_days", "trek_id")
    op.drop_column("itinerary_days", "day_type")
    op.add_column(
        "itineraries",
        sa.Column("submitted_at", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "itineraries", type_="foreignkey")
    op.drop_index(op.f("ix_itineraries_primary_place_id"), table_name="itineraries")
    op.drop_index(op.f("ix_itineraries_itinerary_type"), table_name="itineraries")
    op.drop_index(op.f("ix_itineraries_destination_state"), table_name="itineraries")
    op.drop_index(op.f("ix_itineraries_destination_country"), table_name="itineraries")
    op.drop_index(op.f("ix_itineraries_destination_city"), table_name="itineraries")
    op.drop_column("itineraries", "destination_country")
    op.drop_column("itineraries", "destination_state")
    op.drop_column("itineraries", "destination_city")
    op.drop_column("itineraries", "primary_place_id")
    op.drop_column("itineraries", "itinerary_type")

    # Drop places table
    op.drop_index(op.f("ix_places_updated_at"), table_name="places")
    op.drop_index(op.f("ix_places_state"), table_name="places")
    op.drop_index(op.f("ix_places_safety_rating"), table_name="places")
    op.drop_index(op.f("ix_places_place_type"), table_name="places")
    op.drop_index(op.f("ix_places_name"), table_name="places")
    op.drop_index(op.f("ix_places_id"), table_name="places")
    op.drop_index(op.f("ix_places_difficulty_level"), table_name="places")
    op.drop_index(op.f("ix_places_created_at"), table_name="places")
    op.drop_index(op.f("ix_places_country"), table_name="places")
    op.drop_index(op.f("ix_places_city"), table_name="places")
    op.drop_table("places")

    # Don't recreate spatial_ref_sys - it's a PostGIS system table
    # ### end Alembic commands ###
