"""add blockchain id tables

Revision ID: 5309dd9a2417
Revises: 6ebcece9f613
Create Date: 2025-09-25 23:18:51.332007

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "5309dd9a2417"
down_revision: Union[str, Sequence[str], None] = "6ebcece9f613"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "blockchain_applications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "application_number",
            sqlmodel.sql.sqltypes.AutoString(length=50),
            nullable=False,
        ),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("itinerary_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING", "ISSUED", "REJECTED", name="blockchainapplicationstatusenum"
            ),
            nullable=False,
        ),
        sa.Column("applied_at", sa.DateTime(), nullable=False),
        sa.Column("issued_at", sa.DateTime(), nullable=True),
        sa.Column("rejected_at", sa.DateTime(), nullable=True),
        sa.Column("processed_by_admin", sa.Integer(), nullable=True),
        sa.Column(
            "admin_notes", sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["itinerary_id"],
            ["itineraries.id"],
        ),
        sa.ForeignKeyConstraint(
            ["processed_by_admin"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("application_number"),
    )
    op.create_table(
        "blockchain_ids",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "blockchain_id",
            sqlmodel.sql.sqltypes.AutoString(length=100),
            nullable=False,
        ),
        sa.Column("application_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "blockchain_hash",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=False,
        ),
        sa.Column(
            "smart_contract_address",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=True,
        ),
        sa.Column(
            "transaction_hash",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=True,
        ),
        sa.Column("issued_date", sa.DateTime(), nullable=False),
        sa.Column("expiry_date", sa.DateTime(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "qr_code_data", sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["blockchain_applications.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("blockchain_id"),
    )

    # Only create indexes that don't already exist in production
    # The spatial indexes seem to already exist, so we'll skip them to avoid conflicts
    # If needed, these can be created manually or in a separate migration
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Skip dropping indexes that already existed before this migration
    # Only drop the tables we created
    op.drop_table("blockchain_ids")
    op.drop_table("blockchain_applications")
    # ### end Alembic commands ###
