"""initial migration

Revision ID: 5e5e1a055bfd
Revises:
Create Date: 2025-09-07 23:49:57.954109

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = "5e5e1a055bfd"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_revoked", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_refresh_tokens_id"), "refresh_tokens", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_refresh_tokens_token"), "refresh_tokens", ["token"], unique=True
    )
    op.create_index(
        op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("middle_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("last_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("password_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("country_code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("phone_number", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("indian_citizenship", sa.Boolean(), nullable=False),
        sa.Column(
            "aadhar_number_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "passport_number_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "blockchain_address", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("is_kyc_verified", sa.Boolean(), nullable=False),
        sa.Column("is_email_verified", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("ADMIN", "TOURIST", "GUIDE", "SUPER_ADMIN", name="userroleenum"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_users_country_code"), "users", ["country_code"], unique=False
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_first_name"), "users", ["first_name"], unique=False)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(
        op.f("ix_users_phone_number"), "users", ["phone_number"], unique=True
    )
    op.create_table(
        "guides",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("specialties", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("years_of_experience", sa.Integer(), nullable=True),
        sa.Column(
            "certification_level",
            sa.Enum(
                "BASIC",
                "INTERMEDIATE",
                "ADVANCED",
                "EXPERT",
                name="guidecertificationlevelenum",
            ),
            nullable=True,
        ),
        sa.Column(
            "certification_number", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "languages_spoken", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "preferred_trek_regions", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("max_group_size", sa.Integer(), nullable=True),
        sa.Column("daily_rate", sa.Float(), nullable=True),
        sa.Column("license_number", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("insurance_valid_until", sa.Date(), nullable=True),
        sa.Column(
            "emergency_contact_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "emergency_contact_phone", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("average_rating", sa.Float(), nullable=True),
        sa.Column("total_reviews", sa.Integer(), nullable=False),
        sa.Column("total_treks_completed", sa.Integer(), nullable=False),
        sa.Column("is_available", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("profile_completion_percentage", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_guides_id"), "guides", ["id"], unique=False)
    op.create_index(op.f("ix_guides_user_id"), "guides", ["user_id"], unique=True)
    op.create_table(
        "treks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("location", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("city", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("district", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("state", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("duration", sa.Integer(), nullable=False),
        sa.Column("altitude", sa.Integer(), nullable=True),
        sa.Column("nearest_town", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("best_season", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "permits_required", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "equipment_needed", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("safety_tips", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("minimum_age", sa.Integer(), nullable=True),
        sa.Column("maximum_age", sa.Integer(), nullable=True),
        sa.Column("guide_required", sa.Boolean(), nullable=False),
        sa.Column("minimum_people", sa.Integer(), nullable=True),
        sa.Column("maximum_people", sa.Integer(), nullable=True),
        sa.Column("cost_per_person", sa.Float(), nullable=True),
        sa.Column(
            "difficulty_level",
            sa.Enum("EASY", "MEDIUM", "HARD", name="difficultylevelenum"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_treks_altitude"), "treks", ["altitude"], unique=False)
    op.create_index(op.f("ix_treks_city"), "treks", ["city"], unique=False)
    op.create_index(
        op.f("ix_treks_cost_per_person"), "treks", ["cost_per_person"], unique=False
    )
    op.create_index(op.f("ix_treks_created_at"), "treks", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_treks_created_by_id"), "treks", ["created_by_id"], unique=False
    )
    op.create_index(
        op.f("ix_treks_difficulty_level"), "treks", ["difficulty_level"], unique=False
    )
    op.create_index(op.f("ix_treks_district"), "treks", ["district"], unique=False)
    op.create_index(op.f("ix_treks_duration"), "treks", ["duration"], unique=False)
    op.create_index(
        op.f("ix_treks_guide_required"), "treks", ["guide_required"], unique=False
    )
    op.create_index(op.f("ix_treks_id"), "treks", ["id"], unique=False)
    op.create_index(op.f("ix_treks_location"), "treks", ["location"], unique=False)
    op.create_index(
        op.f("ix_treks_maximum_age"), "treks", ["maximum_age"], unique=False
    )
    op.create_index(
        op.f("ix_treks_maximum_people"), "treks", ["maximum_people"], unique=False
    )
    op.create_index(
        op.f("ix_treks_minimum_age"), "treks", ["minimum_age"], unique=False
    )
    op.create_index(
        op.f("ix_treks_minimum_people"), "treks", ["minimum_people"], unique=False
    )
    op.create_index(op.f("ix_treks_name"), "treks", ["name"], unique=False)
    op.create_index(
        op.f("ix_treks_nearest_town"), "treks", ["nearest_town"], unique=False
    )
    op.create_index(op.f("ix_treks_state"), "treks", ["state"], unique=False)
    op.create_table(
        "guide_treks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("guide_id", sa.Integer(), nullable=False),
        sa.Column("trek_id", sa.Integer(), nullable=False),
        sa.Column("assigned_at", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["guide_id"],
            ["guides.id"],
        ),
        sa.ForeignKeyConstraint(
            ["trek_id"],
            ["treks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_guide_treks_assigned_at"), "guide_treks", ["assigned_at"], unique=False
    )
    op.create_index(
        op.f("ix_guide_treks_guide_id"), "guide_treks", ["guide_id"], unique=False
    )
    op.create_index(op.f("ix_guide_treks_id"), "guide_treks", ["id"], unique=False)
    op.create_index(
        op.f("ix_guide_treks_is_active"), "guide_treks", ["is_active"], unique=False
    )
    op.create_index(
        op.f("ix_guide_treks_trek_id"), "guide_treks", ["trek_id"], unique=False
    )
    op.create_table(
        "tracking_devices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("device_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("api_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("treck_id", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE", "INACTIVE", "MAINTENANCE", name="trackingdevicestatusenum"
            ),
            nullable=False,
        ),
        sa.Column(
            "last_known_location", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("battery_level", sa.Float(), nullable=True),
        sa.Column("signal_strength", sa.Float(), nullable=True),
        sa.Column("activated_at", sa.Integer(), nullable=True),
        sa.Column("deactivated_at", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["treck_id"],
            ["treks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tracking_devices_api_key"),
        "tracking_devices",
        ["api_key"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tracking_devices_created_at"),
        "tracking_devices",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tracking_devices_device_id"),
        "tracking_devices",
        ["device_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_tracking_devices_id"), "tracking_devices", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_tracking_devices_status"), "tracking_devices", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_tracking_devices_treck_id"),
        "tracking_devices",
        ["treck_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tracking_devices_updated_at"),
        "tracking_devices",
        ["updated_at"],
        unique=False,
    )
    op.create_table(
        "trek_route_data",
        sa.Column("trek_id", sa.Integer(), nullable=False),
        sa.Column(
            "route",
            geoalchemy2.types.Geometry(
                geometry_type="LINESTRING",
                srid=4326,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["trek_id"],
            ["treks.id"],
        ),
        sa.PrimaryKeyConstraint("trek_id"),
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_trek_route_data_route ON trek_route_data USING gist (route)"
    )
    op.create_index(
        op.f("ix_trek_route_data_created_at"),
        "trek_route_data",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_trek_route_data_trek_id"), "trek_route_data", ["trek_id"], unique=False
    )
    op.create_index(
        op.f("ix_trek_route_data_updated_at"),
        "trek_route_data",
        ["updated_at"],
        unique=False,
    )
    op.create_table(
        "trips",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("trek_id", sa.Integer(), nullable=False),
        sa.Column("guide_id", sa.Integer(), nullable=True),
        sa.Column("tracking_deivce_id", sa.Integer(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "ASSIGNED",
                "IN_PROGRESS",
                "COMPLETED",
                "CANCELLED",
                name="tripstatusenum",
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["guide_id"],
            ["guides.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tracking_deivce_id"],
            ["tracking_devices.id"],
        ),
        sa.ForeignKeyConstraint(
            ["trek_id"],
            ["treks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_trips_end_date"), "trips", ["end_date"], unique=False)
    op.create_index(op.f("ix_trips_guide_id"), "trips", ["guide_id"], unique=False)
    op.create_index(op.f("ix_trips_id"), "trips", ["id"], unique=False)
    op.create_index(op.f("ix_trips_start_date"), "trips", ["start_date"], unique=False)
    op.create_index(op.f("ix_trips_status"), "trips", ["status"], unique=False)
    op.create_index(
        op.f("ix_trips_tracking_deivce_id"),
        "trips",
        ["tracking_deivce_id"],
        unique=False,
    )
    op.create_index(op.f("ix_trips_trek_id"), "trips", ["trek_id"], unique=False)
    op.create_index(op.f("ix_trips_user_id"), "trips", ["user_id"], unique=False)
    op.create_table(
        "alerts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("trip_id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.Integer(), nullable=False),
        sa.Column(
            "alert_type",
            sa.Enum("DEVIATION", "EMERGENCY", "WEATHER", "OTHER", name="alerttypeenum"),
            nullable=False,
        ),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "location",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.Enum("NEW", "ACKNOWLEDGED", "RESOLVED", name="alertstatusenum"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["trip_id"],
            ["trips.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_alerts_location ON alerts USING gist (location)"
    )

    op.create_index(
        op.f("ix_alerts_alert_type"), "alerts", ["alert_type"], unique=False
    )
    op.create_index(op.f("ix_alerts_id"), "alerts", ["id"], unique=False)
    op.create_index(op.f("ix_alerts_status"), "alerts", ["status"], unique=False)
    op.create_index(op.f("ix_alerts_timestamp"), "alerts", ["timestamp"], unique=False)
    op.create_index(op.f("ix_alerts_trip_id"), "alerts", ["trip_id"], unique=False)
    op.create_table(
        "location_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("trip_id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.Integer(), nullable=False),
        sa.Column(
            "location",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["trip_id"],
            ["trips.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_location_history_location ON location_history USING gist (location)"
    )
    op.create_index(
        op.f("ix_location_history_id"), "location_history", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_location_history_timestamp"),
        "location_history",
        ["timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_location_history_trip_id"),
        "location_history",
        ["trip_id"],
        unique=False,
    )
    # op.drop_table("spatial_ref_sys")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "spatial_ref_sys",
        sa.Column("srid", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "auth_name", sa.VARCHAR(length=256), autoincrement=False, nullable=True
        ),
        sa.Column("auth_srid", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "srtext", sa.VARCHAR(length=2048), autoincrement=False, nullable=True
        ),
        sa.Column(
            "proj4text", sa.VARCHAR(length=2048), autoincrement=False, nullable=True
        ),
        sa.CheckConstraint(
            "srid > 0 AND srid <= 998999", name=op.f("spatial_ref_sys_srid_check")
        ),
        sa.PrimaryKeyConstraint("srid", name=op.f("spatial_ref_sys_pkey")),
    )
    op.drop_index(op.f("ix_location_history_trip_id"), table_name="location_history")
    op.drop_index(op.f("ix_location_history_timestamp"), table_name="location_history")
    op.drop_index(op.f("ix_location_history_id"), table_name="location_history")
    op.drop_index(
        "idx_location_history_location",
        table_name="location_history",
        postgresql_using="gist",
    )
    op.drop_table("location_history")
    op.drop_index(op.f("ix_alerts_trip_id"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_timestamp"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_status"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_id"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_alert_type"), table_name="alerts")
    op.drop_index("idx_alerts_location", table_name="alerts", postgresql_using="gist")
    op.drop_table("alerts")
    op.drop_index(op.f("ix_trips_user_id"), table_name="trips")
    op.drop_index(op.f("ix_trips_trek_id"), table_name="trips")
    op.drop_index(op.f("ix_trips_tracking_deivce_id"), table_name="trips")
    op.drop_index(op.f("ix_trips_status"), table_name="trips")
    op.drop_index(op.f("ix_trips_start_date"), table_name="trips")
    op.drop_index(op.f("ix_trips_id"), table_name="trips")
    op.drop_index(op.f("ix_trips_guide_id"), table_name="trips")
    op.drop_index(op.f("ix_trips_end_date"), table_name="trips")
    op.drop_table("trips")
    op.drop_index(op.f("ix_trek_route_data_updated_at"), table_name="trek_route_data")
    op.drop_index(op.f("ix_trek_route_data_trek_id"), table_name="trek_route_data")
    op.drop_index(op.f("ix_trek_route_data_created_at"), table_name="trek_route_data")
    op.drop_index(
        "idx_trek_route_data_route",
        table_name="trek_route_data",
        postgresql_using="gist",
    )
    op.drop_table("trek_route_data")
    op.drop_index(op.f("ix_tracking_devices_updated_at"), table_name="tracking_devices")
    op.drop_index(op.f("ix_tracking_devices_treck_id"), table_name="tracking_devices")
    op.drop_index(op.f("ix_tracking_devices_status"), table_name="tracking_devices")
    op.drop_index(op.f("ix_tracking_devices_id"), table_name="tracking_devices")
    op.drop_index(op.f("ix_tracking_devices_device_id"), table_name="tracking_devices")
    op.drop_index(op.f("ix_tracking_devices_created_at"), table_name="tracking_devices")
    op.drop_index(op.f("ix_tracking_devices_api_key"), table_name="tracking_devices")
    op.drop_table("tracking_devices")
    op.drop_index(op.f("ix_guide_treks_trek_id"), table_name="guide_treks")
    op.drop_index(op.f("ix_guide_treks_is_active"), table_name="guide_treks")
    op.drop_index(op.f("ix_guide_treks_id"), table_name="guide_treks")
    op.drop_index(op.f("ix_guide_treks_guide_id"), table_name="guide_treks")
    op.drop_index(op.f("ix_guide_treks_assigned_at"), table_name="guide_treks")
    op.drop_table("guide_treks")
    op.drop_index(op.f("ix_treks_state"), table_name="treks")
    op.drop_index(op.f("ix_treks_nearest_town"), table_name="treks")
    op.drop_index(op.f("ix_treks_name"), table_name="treks")
    op.drop_index(op.f("ix_treks_minimum_people"), table_name="treks")
    op.drop_index(op.f("ix_treks_minimum_age"), table_name="treks")
    op.drop_index(op.f("ix_treks_maximum_people"), table_name="treks")
    op.drop_index(op.f("ix_treks_maximum_age"), table_name="treks")
    op.drop_index(op.f("ix_treks_location"), table_name="treks")
    op.drop_index(op.f("ix_treks_id"), table_name="treks")
    op.drop_index(op.f("ix_treks_guide_required"), table_name="treks")
    op.drop_index(op.f("ix_treks_duration"), table_name="treks")
    op.drop_index(op.f("ix_treks_district"), table_name="treks")
    op.drop_index(op.f("ix_treks_difficulty_level"), table_name="treks")
    op.drop_index(op.f("ix_treks_created_by_id"), table_name="treks")
    op.drop_index(op.f("ix_treks_created_at"), table_name="treks")
    op.drop_index(op.f("ix_treks_cost_per_person"), table_name="treks")
    op.drop_index(op.f("ix_treks_city"), table_name="treks")
    op.drop_index(op.f("ix_treks_altitude"), table_name="treks")
    op.drop_table("treks")
    op.drop_index(op.f("ix_guides_user_id"), table_name="guides")
    op.drop_index(op.f("ix_guides_id"), table_name="guides")
    op.drop_table("guides")
    op.drop_index(op.f("ix_users_phone_number"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_first_name"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_country_code"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_token"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_id"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    # ### end Alembic commands ###
