"""Initial Commit

Revision ID: 658d9ba25f3d
Revises:
Create Date: 2025-09-19 10:15:43.718419

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = "658d9ba25f3d"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis;")
    op.create_table(
        "accommodations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("address", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("city", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("state", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("postal_code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "location",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_accommodations_location ON accommodations USING gist (location);"
    )
    op.create_index(
        op.f("ix_accommodations_address"), "accommodations", ["address"], unique=False
    )
    op.create_index(
        op.f("ix_accommodations_city"), "accommodations", ["city"], unique=False
    )
    op.create_index(
        op.f("ix_accommodations_id"), "accommodations", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_accommodations_name"), "accommodations", ["name"], unique=False
    )
    op.create_index(
        op.f("ix_accommodations_postal_code"),
        "accommodations",
        ["postal_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_accommodations_state"), "accommodations", ["state"], unique=False
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_revoked", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_refresh_tokens_id"), "refresh_tokens", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_refresh_tokens_token"), "refresh_tokens", ["token"], unique=True
    )
    op.create_index(
        op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False
    )
    op.create_table(
        "tracking_devices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("api_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tracking_devices_api_key"),
        "tracking_devices",
        ["api_key"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tracking_devices_created_at"),
        "tracking_devices",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tracking_devices_id"), "tracking_devices", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_tracking_devices_updated_at"),
        "tracking_devices",
        ["updated_at"],
        unique=False,
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("middle_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("last_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("password_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("country_code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("phone_number", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "aadhar_number_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "passport_number_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "blockchain_address", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("is_kyc_verified", sa.Boolean(), nullable=False),
        sa.Column("is_email_verified", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "special_requirment", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "emergency_contact_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "emergency_contact_phone", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "emergency_contact_relation",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
        ),
        sa.Column(
            "role",
            sa.Enum("ADMIN", "TOURIST", "GUIDE", "SUPER_ADMIN", name="userroleenum"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_users_country_code"), "users", ["country_code"], unique=False
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_first_name"), "users", ["first_name"], unique=False)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(
        op.f("ix_users_phone_number"), "users", ["phone_number"], unique=True
    )
    op.create_table(
        "guides",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_guides_id"), "guides", ["id"], unique=False)
    op.create_index(op.f("ix_guides_user_id"), "guides", ["user_id"], unique=True)
    op.create_table(
        "itineraries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "destination_city", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "destination_state", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("total_duration_days", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_itineraries_created_at"), "itineraries", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_itineraries_destination_city"),
        "itineraries",
        ["destination_city"],
        unique=False,
    )
    op.create_index(
        op.f("ix_itineraries_destination_state"),
        "itineraries",
        ["destination_state"],
        unique=False,
    )
    op.create_index(
        op.f("ix_itineraries_end_date"), "itineraries", ["end_date"], unique=False
    )
    op.create_index(op.f("ix_itineraries_id"), "itineraries", ["id"], unique=False)
    op.create_index(
        op.f("ix_itineraries_start_date"), "itineraries", ["start_date"], unique=False
    )
    op.create_index(
        op.f("ix_itineraries_title"), "itineraries", ["title"], unique=False
    )
    op.create_index(
        op.f("ix_itineraries_total_duration_days"),
        "itineraries",
        ["total_duration_days"],
        unique=False,
    )
    op.create_index(
        op.f("ix_itineraries_updated_at"), "itineraries", ["updated_at"], unique=False
    )
    op.create_index(
        op.f("ix_itineraries_user_id"), "itineraries", ["user_id"], unique=False
    )
    op.create_table(
        "offline_activities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "location",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.Column("city", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("district", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("state", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("duration", sa.Integer(), nullable=True),
        sa.Column("altitude", sa.Integer(), nullable=True),
        sa.Column("nearest_town", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("best_season", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "permits_required", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "equipment_needed", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("safety_tips", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("minimum_age", sa.Integer(), nullable=True),
        sa.Column("maximum_age", sa.Integer(), nullable=True),
        sa.Column("guide_required", sa.Boolean(), nullable=False),
        sa.Column("minimum_people", sa.Integer(), nullable=True),
        sa.Column("maximum_people", sa.Integer(), nullable=True),
        sa.Column("cost_per_person", sa.Float(), nullable=True),
        sa.Column(
            "difficulty_level",
            sa.Enum("EASY", "MEDIUM", "HARD", name="difficultylevelenum"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_offline_activities_location ON offline_activities USING gist (location);"
    )
    op.create_index(
        op.f("ix_offline_activities_altitude"),
        "offline_activities",
        ["altitude"],
        unique=False,
    )
    op.create_index(
        op.f("ix_offline_activities_city"), "offline_activities", ["city"], unique=False
    )
    op.create_index(
        op.f("ix_offline_activities_created_at"),
        "offline_activities",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_offline_activities_created_by"),
        "offline_activities",
        ["created_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_offline_activities_difficulty_level"),
        "offline_activities",
        ["difficulty_level"],
        unique=False,
    )
    op.create_index(
        op.f("ix_offline_activities_district"),
        "offline_activities",
        ["district"],
        unique=False,
    )
    op.create_index(
        op.f("ix_offline_activities_duration"),
        "offline_activities",
        ["duration"],
        unique=False,
    )
    op.create_index(
        op.f("ix_offline_activities_id"), "offline_activities", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_offline_activities_name"), "offline_activities", ["name"], unique=False
    )
    op.create_index(
        op.f("ix_offline_activities_state"),
        "offline_activities",
        ["state"],
        unique=False,
    )
    op.create_index(
        op.f("ix_offline_activities_updated_at"),
        "offline_activities",
        ["updated_at"],
        unique=False,
    )
    op.create_table(
        "online_activities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "place_type",
            sa.Enum(
                "HISTORICAL_SITE",
                "TEMPLE",
                "MUSEUM",
                "PARK",
                "ADVENTURE_SPORT",
                "CULTURAL_SITE",
                "RESTAURANT",
                "SHOPPING",
                "NIGHTLIFE",
                name="onlineactivitytypeenum",
            ),
            nullable=False,
        ),
        sa.Column("city", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("state", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("address", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "location",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.Column("cost_per_person", sa.Float(), nullable=True),
        sa.Column("wheelchair_accessible", sa.Boolean(), nullable=False),
        sa.Column("safety_rating", sa.Integer(), nullable=True),
        sa.Column("contact_number", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("website", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("opening_time", sa.Time(), nullable=False),
        sa.Column("closing_time", sa.Time(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_online_activities_location ON online_activities USING gist (location);"
    )
    op.create_index(
        op.f("ix_online_activities_city"), "online_activities", ["city"], unique=False
    )
    op.create_index(
        op.f("ix_online_activities_cost_per_person"),
        "online_activities",
        ["cost_per_person"],
        unique=False,
    )
    op.create_index(
        op.f("ix_online_activities_created_at"),
        "online_activities",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_online_activities_created_by"),
        "online_activities",
        ["created_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_online_activities_id"), "online_activities", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_online_activities_is_active"),
        "online_activities",
        ["is_active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_online_activities_name"), "online_activities", ["name"], unique=False
    )
    op.create_index(
        op.f("ix_online_activities_place_type"),
        "online_activities",
        ["place_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_online_activities_state"), "online_activities", ["state"], unique=False
    )
    op.create_index(
        op.f("ix_online_activities_updated_at"),
        "online_activities",
        ["updated_at"],
        unique=False,
    )
    op.create_table(
        "restricted_areas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "area_type",
            sa.Enum(
                "RESTRICTED_ZONE",
                "DANGER_ZONE",
                "PRIVATE_PROPERTY",
                "PROTECTED_AREA",
                "MILITARY_ZONE",
                "SEASONAL_CLOSURE",
                name="restrictedareatypeenum",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "INACTIVE",
                "TEMPORARILY_DISABLED",
                name="restrictedareastatusenum",
            ),
            nullable=False,
        ),
        sa.Column(
            "boundary",
            geoalchemy2.types.Geometry(
                geometry_type="POLYGON",
                srid=4326,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.Column("created_by_admin_id", sa.Integer(), nullable=False),
        sa.Column("severity_level", sa.Integer(), nullable=False),
        sa.Column(
            "restriction_reason", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("contact_info", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("valid_from", sa.DateTime(), nullable=True),
        sa.Column("valid_until", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("send_warning_notification", sa.Boolean(), nullable=False),
        sa.Column("auto_alert_authorities", sa.Boolean(), nullable=False),
        sa.Column("buffer_distance_meters", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_admin_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_restricted_areas_boundary ON restricted_areas USING gist (boundary);"
    )
    op.create_index(
        op.f("ix_restricted_areas_area_type"),
        "restricted_areas",
        ["area_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_restricted_areas_created_at"),
        "restricted_areas",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_restricted_areas_created_by_admin_id"),
        "restricted_areas",
        ["created_by_admin_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_restricted_areas_id"), "restricted_areas", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_restricted_areas_name"), "restricted_areas", ["name"], unique=False
    )
    op.create_index(
        op.f("ix_restricted_areas_status"), "restricted_areas", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_restricted_areas_updated_at"),
        "restricted_areas",
        ["updated_at"],
        unique=False,
    )
    op.create_table(
        "itinerary_days",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("itinerary_id", sa.Integer(), nullable=False),
        sa.Column("accommodation_id", sa.Integer(), nullable=False),
        sa.Column("day_number", sa.Integer(), nullable=False),
        sa.Column("offline_activity_id", sa.Integer(), nullable=True),
        sa.Column("online_activity_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["accommodation_id"],
            ["accommodations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["itinerary_id"],
            ["itineraries.id"],
        ),
        sa.ForeignKeyConstraint(
            ["offline_activity_id"],
            ["offline_activities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["online_activity_id"],
            ["online_activities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_itinerary_days_accommodation_id"),
        "itinerary_days",
        ["accommodation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_itinerary_days_day_number"),
        "itinerary_days",
        ["day_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_itinerary_days_id"), "itinerary_days", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_itinerary_days_itinerary_id"),
        "itinerary_days",
        ["itinerary_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_itinerary_days_offline_activity_id"),
        "itinerary_days",
        ["offline_activity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_itinerary_days_online_activity_id"),
        "itinerary_days",
        ["online_activity_id"],
        unique=False,
    )
    op.create_table(
        "offline_activity_route_data",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("offline_activity_id", sa.Integer(), nullable=False),
        sa.Column(
            "route",
            geoalchemy2.types.Geometry(
                geometry_type="LINESTRING",
                srid=4326,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.Column("route_data", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["offline_activity_id"],
            ["offline_activities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_offline_activity_route_data_route ON offline_activity_route_data USING gist (route);"
    )
    op.create_index(
        op.f("ix_offline_activity_route_data_created_at"),
        "offline_activity_route_data",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_offline_activity_route_data_id"),
        "offline_activity_route_data",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_offline_activity_route_data_offline_activity_id"),
        "offline_activity_route_data",
        ["offline_activity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_offline_activity_route_data_updated_at"),
        "offline_activity_route_data",
        ["updated_at"],
        unique=False,
    )
    op.create_table(
        "trips",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("itinerary_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "UPCOMING", "ONGOING", "COMPLETED", "CANCELLED", name="tripstatusenum"
            ),
            nullable=False,
        ),
        sa.Column("tourist_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "blockchain_transaction_hash",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["itinerary_id"],
            ["itineraries.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_trips_blockchain_transaction_hash"),
        "trips",
        ["blockchain_transaction_hash"],
        unique=False,
    )
    op.create_index(op.f("ix_trips_created_at"), "trips", ["created_at"], unique=False)
    op.create_index(op.f("ix_trips_id"), "trips", ["id"], unique=False)
    op.create_index(
        op.f("ix_trips_itinerary_id"), "trips", ["itinerary_id"], unique=False
    )
    op.create_index(op.f("ix_trips_status"), "trips", ["status"], unique=False)
    op.create_index(op.f("ix_trips_tourist_id"), "trips", ["tourist_id"], unique=False)
    op.create_index(op.f("ix_trips_updated_at"), "trips", ["updated_at"], unique=False)
    op.create_index(op.f("ix_trips_user_id"), "trips", ["user_id"], unique=False)
    op.create_table(
        "geofence_violations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("restricted_area_id", sa.Integer(), nullable=False),
        sa.Column("trip_id", sa.Integer(), nullable=True),
        sa.Column("violation_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "violation_location",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.Column("detected_at", sa.DateTime(), nullable=False),
        sa.Column("resolved_at", sa.DateTime(), nullable=True),
        sa.Column("notification_sent", sa.Boolean(), nullable=False),
        sa.Column("authorities_alerted", sa.Boolean(), nullable=False),
        sa.Column("severity_score", sa.Integer(), nullable=False),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("resolved_by_admin_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["resolved_by_admin_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["restricted_area_id"],
            ["restricted_areas.id"],
        ),
        sa.ForeignKeyConstraint(
            ["trip_id"],
            ["trips.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_geofence_violations_violation_location ON geofence_violations USING gist (violation_location);"
    )
    op.create_index(
        op.f("ix_geofence_violations_detected_at"),
        "geofence_violations",
        ["detected_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_geofence_violations_id"), "geofence_violations", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_geofence_violations_restricted_area_id"),
        "geofence_violations",
        ["restricted_area_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_geofence_violations_trip_id"),
        "geofence_violations",
        ["trip_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_geofence_violations_user_id"),
        "geofence_violations",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_geofence_violations_violation_type"),
        "geofence_violations",
        ["violation_type"],
        unique=False,
    )
    op.create_table(
        "location_histories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("trip_id", sa.Integer(), nullable=False),
        sa.Column(
            "location",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["trip_id"],
            ["trips.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_location_histories_location ON location_histories USING gist (location);"
    )
    op.create_index(
        op.f("ix_location_histories_id"), "location_histories", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_location_histories_timestamp"),
        "location_histories",
        ["timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_location_histories_trip_id"),
        "location_histories",
        ["trip_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_location_histories_user_id"),
        "location_histories",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP EXTENSION IF EXISTS postgis;")
    op.drop_index(
        op.f("ix_location_histories_user_id"), table_name="location_histories"
    )
    op.drop_index(
        op.f("ix_location_histories_trip_id"), table_name="location_histories"
    )
    op.drop_index(
        op.f("ix_location_histories_timestamp"), table_name="location_histories"
    )
    op.drop_index(
        op.f("ix_location_histories_location"), table_name="location_histories"
    )
    op.drop_index(op.f("ix_location_histories_id"), table_name="location_histories")
    op.drop_index(
        "idx_location_histories_location",
        table_name="location_histories",
        postgresql_using="gist",
    )
    op.drop_table("location_histories")
    op.drop_index(
        op.f("ix_geofence_violations_violation_type"), table_name="geofence_violations"
    )
    op.drop_index(
        op.f("ix_geofence_violations_user_id"), table_name="geofence_violations"
    )
    op.drop_index(
        op.f("ix_geofence_violations_trip_id"), table_name="geofence_violations"
    )
    op.drop_index(
        op.f("ix_geofence_violations_restricted_area_id"),
        table_name="geofence_violations",
    )
    op.drop_index(op.f("ix_geofence_violations_id"), table_name="geofence_violations")
    op.drop_index(
        op.f("ix_geofence_violations_detected_at"), table_name="geofence_violations"
    )
    op.drop_index(
        "idx_geofence_violations_violation_location",
        table_name="geofence_violations",
        postgresql_using="gist",
    )
    op.drop_table("geofence_violations")
    op.drop_index(op.f("ix_trips_user_id"), table_name="trips")
    op.drop_index(op.f("ix_trips_updated_at"), table_name="trips")
    op.drop_index(op.f("ix_trips_tourist_id"), table_name="trips")
    op.drop_index(op.f("ix_trips_status"), table_name="trips")
    op.drop_index(op.f("ix_trips_itinerary_id"), table_name="trips")
    op.drop_index(op.f("ix_trips_id"), table_name="trips")
    op.drop_index(op.f("ix_trips_created_at"), table_name="trips")
    op.drop_index(op.f("ix_trips_blockchain_transaction_hash"), table_name="trips")
    op.drop_table("trips")
    op.drop_index(
        op.f("ix_offline_activity_route_data_updated_at"),
        table_name="offline_activity_route_data",
    )
    op.drop_index(
        op.f("ix_offline_activity_route_data_route"),
        table_name="offline_activity_route_data",
    )
    op.drop_index(
        op.f("ix_offline_activity_route_data_offline_activity_id"),
        table_name="offline_activity_route_data",
    )
    op.drop_index(
        op.f("ix_offline_activity_route_data_id"),
        table_name="offline_activity_route_data",
    )
    op.drop_index(
        op.f("ix_offline_activity_route_data_created_at"),
        table_name="offline_activity_route_data",
    )
    op.drop_index(
        "idx_offline_activity_route_data_route",
        table_name="offline_activity_route_data",
        postgresql_using="gist",
    )
    op.drop_table("offline_activity_route_data")
    op.drop_index(
        op.f("ix_itinerary_days_online_activity_id"), table_name="itinerary_days"
    )
    op.drop_index(
        op.f("ix_itinerary_days_offline_activity_id"), table_name="itinerary_days"
    )
    op.drop_index(op.f("ix_itinerary_days_itinerary_id"), table_name="itinerary_days")
    op.drop_index(op.f("ix_itinerary_days_id"), table_name="itinerary_days")
    op.drop_index(op.f("ix_itinerary_days_day_number"), table_name="itinerary_days")
    op.drop_index(
        op.f("ix_itinerary_days_accommodation_id"), table_name="itinerary_days"
    )
    op.drop_table("itinerary_days")
    op.drop_index(op.f("ix_restricted_areas_updated_at"), table_name="restricted_areas")
    op.drop_index(op.f("ix_restricted_areas_status"), table_name="restricted_areas")
    op.drop_index(op.f("ix_restricted_areas_name"), table_name="restricted_areas")
    op.drop_index(op.f("ix_restricted_areas_id"), table_name="restricted_areas")
    op.drop_index(
        op.f("ix_restricted_areas_created_by_admin_id"), table_name="restricted_areas"
    )
    op.drop_index(op.f("ix_restricted_areas_created_at"), table_name="restricted_areas")
    op.drop_index(op.f("ix_restricted_areas_area_type"), table_name="restricted_areas")
    op.drop_index(
        "idx_restricted_areas_boundary",
        table_name="restricted_areas",
        postgresql_using="gist",
    )
    op.drop_table("restricted_areas")
    op.drop_index(
        op.f("ix_online_activities_updated_at"), table_name="online_activities"
    )
    op.drop_index(op.f("ix_online_activities_state"), table_name="online_activities")
    op.drop_index(
        op.f("ix_online_activities_place_type"), table_name="online_activities"
    )
    op.drop_index(op.f("ix_online_activities_name"), table_name="online_activities")
    op.drop_index(op.f("ix_online_activities_location"), table_name="online_activities")
    op.drop_index(
        op.f("ix_online_activities_is_active"), table_name="online_activities"
    )
    op.drop_index(op.f("ix_online_activities_id"), table_name="online_activities")
    op.drop_index(
        op.f("ix_online_activities_created_by"), table_name="online_activities"
    )
    op.drop_index(
        op.f("ix_online_activities_created_at"), table_name="online_activities"
    )
    op.drop_index(
        op.f("ix_online_activities_cost_per_person"), table_name="online_activities"
    )
    op.drop_index(op.f("ix_online_activities_city"), table_name="online_activities")
    op.drop_index(
        "idx_online_activities_location",
        table_name="online_activities",
        postgresql_using="gist",
    )
    op.drop_table("online_activities")
    op.drop_index(
        op.f("ix_offline_activities_updated_at"), table_name="offline_activities"
    )
    op.drop_index(op.f("ix_offline_activities_state"), table_name="offline_activities")
    op.drop_index(op.f("ix_offline_activities_name"), table_name="offline_activities")
    op.drop_index(
        op.f("ix_offline_activities_location"), table_name="offline_activities"
    )
    op.drop_index(op.f("ix_offline_activities_id"), table_name="offline_activities")
    op.drop_index(
        op.f("ix_offline_activities_duration"), table_name="offline_activities"
    )
    op.drop_index(
        op.f("ix_offline_activities_district"), table_name="offline_activities"
    )
    op.drop_index(
        op.f("ix_offline_activities_difficulty_level"), table_name="offline_activities"
    )
    op.drop_index(
        op.f("ix_offline_activities_created_by"), table_name="offline_activities"
    )
    op.drop_index(
        op.f("ix_offline_activities_created_at"), table_name="offline_activities"
    )
    op.drop_index(op.f("ix_offline_activities_city"), table_name="offline_activities")
    op.drop_index(
        op.f("ix_offline_activities_altitude"), table_name="offline_activities"
    )
    op.drop_index(
        "idx_offline_activities_location",
        table_name="offline_activities",
        postgresql_using="gist",
    )
    op.drop_table("offline_activities")
    op.drop_index(op.f("ix_itineraries_user_id"), table_name="itineraries")
    op.drop_index(op.f("ix_itineraries_updated_at"), table_name="itineraries")
    op.drop_index(op.f("ix_itineraries_total_duration_days"), table_name="itineraries")
    op.drop_index(op.f("ix_itineraries_title"), table_name="itineraries")
    op.drop_index(op.f("ix_itineraries_start_date"), table_name="itineraries")
    op.drop_index(op.f("ix_itineraries_id"), table_name="itineraries")
    op.drop_index(op.f("ix_itineraries_end_date"), table_name="itineraries")
    op.drop_index(op.f("ix_itineraries_destination_state"), table_name="itineraries")
    op.drop_index(op.f("ix_itineraries_destination_city"), table_name="itineraries")
    op.drop_index(op.f("ix_itineraries_created_at"), table_name="itineraries")
    op.drop_table("itineraries")
    op.drop_index(op.f("ix_guides_user_id"), table_name="guides")
    op.drop_index(op.f("ix_guides_id"), table_name="guides")
    op.drop_table("guides")
    op.drop_index(op.f("ix_users_phone_number"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_first_name"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_country_code"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_tracking_devices_updated_at"), table_name="tracking_devices")
    op.drop_index(op.f("ix_tracking_devices_id"), table_name="tracking_devices")
    op.drop_index(op.f("ix_tracking_devices_created_at"), table_name="tracking_devices")
    op.drop_index(op.f("ix_tracking_devices_api_key"), table_name="tracking_devices")
    op.drop_table("tracking_devices")
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_token"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_id"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index(op.f("ix_accommodations_state"), table_name="accommodations")
    op.drop_index(op.f("ix_accommodations_postal_code"), table_name="accommodations")
    op.drop_index(op.f("ix_accommodations_name"), table_name="accommodations")
    op.drop_index(op.f("ix_accommodations_location"), table_name="accommodations")
    op.drop_index(op.f("ix_accommodations_id"), table_name="accommodations")
    op.drop_index(op.f("ix_accommodations_city"), table_name="accommodations")
    op.drop_index(op.f("ix_accommodations_address"), table_name="accommodations")
    op.drop_index(
        "idx_accommodations_location",
        table_name="accommodations",
        postgresql_using="gist",
    )
    op.drop_table("accommodations")
    # ### end Alembic commands ###
