"""add_tourist_id_fields_to_user

Revision ID: 6c31bc01f9d2
Revises: 5e5e1a055bfd
Create Date: 2025-09-08 03:37:41.914294

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = "6c31bc01f9d2"
down_revision: Union[str, Sequence[str], None] = "5e5e1a055bfd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("tourist_id_token", sa.Integer(), nullable=True))
    op.add_column(
        "users",
        sa.Column(
            "tourist_id_transaction_hash",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "tourist_id_transaction_hash")
    op.drop_column("users", "tourist_id_token")
    # ### end Alembic commands ###
