"""enhance_trip_tracking_with_button_workflow

Revision ID: 6cb22c2bfde4
Revises: 78c82ca8793f
Create Date: 2025-09-10 00:07:12.163249

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "6cb22c2bfde4"
down_revision: Union[str, Sequence[str], None] = "78c82ca8793f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: Removed spatial_ref_sys drop as it's a PostGIS system table

    # Enhanced location_history table
    op.add_column(
        "location_history", sa.Column("user_id", sa.Integer(), nullable=True)
    )  # Allow NULL initially
    op.add_column(
        "location_history", sa.Column("latitude", sa.Float(), nullable=True)
    )  # Allow NULL initially
    op.add_column(
        "location_history", sa.Column("longitude", sa.Float(), nullable=True)
    )  # Allow NULL initially
    op.add_column("location_history", sa.Column("altitude", sa.Float(), nullable=True))
    op.add_column("location_history", sa.Column("accuracy", sa.Float(), nullable=True))
    op.add_column("location_history", sa.Column("speed", sa.Float(), nullable=True))
    op.add_column("location_history", sa.Column("bearing", sa.Float(), nullable=True))
    op.add_column(
        "location_history",
        sa.Column(
            "source",
            sa.Enum(
                "MOBILE_GPS", "TRACKING_DEVICE", "MANUAL", name="locationsourceenum"
            ),
            nullable=True,
        ),
    )  # Allow NULL initially
    op.add_column(
        "location_history",
        sa.Column("trip_phase", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "location_history",
        sa.Column("device_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "location_history", sa.Column("battery_level", sa.Integer(), nullable=True)
    )
    op.add_column(
        "location_history", sa.Column("signal_strength", sa.Integer(), nullable=True)
    )
    op.add_column(
        "location_history",
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "location_history",
        sa.Column("is_waypoint", sa.Boolean(), nullable=True, server_default="false"),
    )  # Default to false
    op.create_index(
        op.f("ix_location_history_device_id"),
        "location_history",
        ["device_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_location_history_is_waypoint"),
        "location_history",
        ["is_waypoint"],
        unique=False,
    )
    op.create_index(
        op.f("ix_location_history_latitude"),
        "location_history",
        ["latitude"],
        unique=False,
    )
    op.create_index(
        op.f("ix_location_history_longitude"),
        "location_history",
        ["longitude"],
        unique=False,
    )
    op.create_index(
        op.f("ix_location_history_source"), "location_history", ["source"], unique=False
    )
    op.create_index(
        op.f("ix_location_history_trip_phase"),
        "location_history",
        ["trip_phase"],
        unique=False,
    )
    op.create_index(
        op.f("ix_location_history_user_id"),
        "location_history",
        ["user_id"],
        unique=False,
    )
    op.create_foreign_key(None, "location_history", "users", ["user_id"], ["id"])

    # Enhanced trips table
    op.add_column(
        "trips",
        sa.Column(
            "trip_type",
            sa.Enum("TREK_DAY", "TOUR_DAY", name="triptypeenum"),
            nullable=True,
        ),
    )  # Allow NULL initially
    op.add_column(
        "trips",
        sa.Column("current_phase", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column("trips", sa.Column("hotel_latitude", sa.Float(), nullable=True))
    op.add_column("trips", sa.Column("hotel_longitude", sa.Float(), nullable=True))
    op.add_column(
        "trips",
        sa.Column("hotel_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column("trips", sa.Column("destination_latitude", sa.Float(), nullable=True))
    op.add_column(
        "trips", sa.Column("destination_longitude", sa.Float(), nullable=True)
    )
    op.add_column(
        "trips",
        sa.Column(
            "destination_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    op.add_column("trips", sa.Column("trek_start_latitude", sa.Float(), nullable=True))
    op.add_column("trips", sa.Column("trek_start_longitude", sa.Float(), nullable=True))
    op.add_column("trips", sa.Column("trek_end_latitude", sa.Float(), nullable=True))
    op.add_column("trips", sa.Column("trek_end_longitude", sa.Float(), nullable=True))
    op.add_column(
        "trips", sa.Column("tracking_started_at", sa.DateTime(), nullable=True)
    )
    op.add_column("trips", sa.Column("tracking_ended_at", sa.DateTime(), nullable=True))
    op.add_column(
        "trips",
        sa.Column(
            "is_tracking_active", sa.Boolean(), nullable=True, server_default="false"
        ),
    )
    op.add_column(
        "trips",
        sa.Column(
            "linked_device_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    op.add_column("trips", sa.Column("device_linked_at", sa.DateTime(), nullable=True))
    op.create_index(
        op.f("ix_trips_current_phase"), "trips", ["current_phase"], unique=False
    )
    op.create_index(
        op.f("ix_trips_destination_latitude"),
        "trips",
        ["destination_latitude"],
        unique=False,
    )
    op.create_index(
        op.f("ix_trips_destination_longitude"),
        "trips",
        ["destination_longitude"],
        unique=False,
    )
    op.create_index(
        op.f("ix_trips_device_linked_at"), "trips", ["device_linked_at"], unique=False
    )
    op.create_index(
        op.f("ix_trips_hotel_latitude"), "trips", ["hotel_latitude"], unique=False
    )
    op.create_index(
        op.f("ix_trips_hotel_longitude"), "trips", ["hotel_longitude"], unique=False
    )
    op.create_index(
        op.f("ix_trips_is_tracking_active"),
        "trips",
        ["is_tracking_active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_trips_linked_device_id"), "trips", ["linked_device_id"], unique=False
    )
    op.create_index(
        op.f("ix_trips_tracking_ended_at"), "trips", ["tracking_ended_at"], unique=False
    )
    op.create_index(
        op.f("ix_trips_tracking_started_at"),
        "trips",
        ["tracking_started_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_trips_trek_end_latitude"), "trips", ["trek_end_latitude"], unique=False
    )
    op.create_index(
        op.f("ix_trips_trek_end_longitude"),
        "trips",
        ["trek_end_longitude"],
        unique=False,
    )
    op.create_index(
        op.f("ix_trips_trek_start_latitude"),
        "trips",
        ["trek_start_latitude"],
        unique=False,
    )
    op.create_index(
        op.f("ix_trips_trek_start_longitude"),
        "trips",
        ["trek_start_longitude"],
        unique=False,
    )
    op.create_index(op.f("ix_trips_trip_type"), "trips", ["trip_type"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_trips_trip_type"), table_name="trips")
    op.drop_index(op.f("ix_trips_trek_start_longitude"), table_name="trips")
    op.drop_index(op.f("ix_trips_trek_start_latitude"), table_name="trips")
    op.drop_index(op.f("ix_trips_trek_end_longitude"), table_name="trips")
    op.drop_index(op.f("ix_trips_trek_end_latitude"), table_name="trips")
    op.drop_index(op.f("ix_trips_tracking_started_at"), table_name="trips")
    op.drop_index(op.f("ix_trips_tracking_ended_at"), table_name="trips")
    op.drop_index(op.f("ix_trips_linked_device_id"), table_name="trips")
    op.drop_index(op.f("ix_trips_is_tracking_active"), table_name="trips")
    op.drop_index(op.f("ix_trips_hotel_longitude"), table_name="trips")
    op.drop_index(op.f("ix_trips_hotel_latitude"), table_name="trips")
    op.drop_index(op.f("ix_trips_device_linked_at"), table_name="trips")
    op.drop_index(op.f("ix_trips_destination_longitude"), table_name="trips")
    op.drop_index(op.f("ix_trips_destination_latitude"), table_name="trips")
    op.drop_index(op.f("ix_trips_current_phase"), table_name="trips")
    op.drop_column("trips", "device_linked_at")
    op.drop_column("trips", "linked_device_id")
    op.drop_column("trips", "is_tracking_active")
    op.drop_column("trips", "tracking_ended_at")
    op.drop_column("trips", "tracking_started_at")
    op.drop_column("trips", "trek_end_longitude")
    op.drop_column("trips", "trek_end_latitude")
    op.drop_column("trips", "trek_start_longitude")
    op.drop_column("trips", "trek_start_latitude")
    op.drop_column("trips", "destination_name")
    op.drop_column("trips", "destination_longitude")
    op.drop_column("trips", "destination_latitude")
    op.drop_column("trips", "hotel_name")
    op.drop_column("trips", "hotel_longitude")
    op.drop_column("trips", "hotel_latitude")
    op.drop_column("trips", "current_phase")
    op.drop_column("trips", "trip_type")
    op.drop_constraint(None, "location_history", type_="foreignkey")
    op.drop_index(op.f("ix_location_history_user_id"), table_name="location_history")
    op.drop_index(op.f("ix_location_history_trip_phase"), table_name="location_history")
    op.drop_index(op.f("ix_location_history_source"), table_name="location_history")
    op.drop_index(op.f("ix_location_history_longitude"), table_name="location_history")
    op.drop_index(op.f("ix_location_history_latitude"), table_name="location_history")
    op.drop_index(
        op.f("ix_location_history_is_waypoint"), table_name="location_history"
    )
    op.drop_index(op.f("ix_location_history_device_id"), table_name="location_history")
    op.drop_column("location_history", "is_waypoint")
    op.drop_column("location_history", "notes")
    op.drop_column("location_history", "signal_strength")
    op.drop_column("location_history", "battery_level")
    op.drop_column("location_history", "device_id")
    op.drop_column("location_history", "trip_phase")
    op.drop_column("location_history", "source")
    op.drop_column("location_history", "bearing")
    op.drop_column("location_history", "speed")
    op.drop_column("location_history", "accuracy")
    op.drop_column("location_history", "altitude")
    op.drop_column("location_history", "longitude")
    op.drop_column("location_history", "latitude")
    op.drop_column("location_history", "user_id")
    op.create_table(
        "spatial_ref_sys",
        sa.Column("srid", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "auth_name", sa.VARCHAR(length=256), autoincrement=False, nullable=True
        ),
        sa.Column("auth_srid", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "srtext", sa.VARCHAR(length=2048), autoincrement=False, nullable=True
        ),
        sa.Column(
            "proj4text", sa.VARCHAR(length=2048), autoincrement=False, nullable=True
        ),
        sa.CheckConstraint(
            "srid > 0 AND srid <= 998999", name=op.f("spatial_ref_sys_srid_check")
        ),
        sa.PrimaryKeyConstraint("srid", name=op.f("spatial_ref_sys_pkey")),
    )
    # ### end Alembic commands ###
