"""Updated Some

Revision ID: 74167a091164
Revises: 784bcee1dbbc
Create Date: 2025-09-17 04:24:03.675261

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "74167a091164"
down_revision: Union[str, Sequence[str], None] = "784bcee1dbbc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "itinerary_days", sa.Column("offline_activity_id", sa.Integer(), nullable=True)
    )
    op.add_column(
        "itinerary_days", sa.Column("online_activity_id", sa.Integer(), nullable=True)
    )
    op.drop_index(op.f("ix_itinerary_days_trek_id"), table_name="itinerary_days")
    op.create_index(
        op.f("ix_itinerary_days_offline_activity_id"),
        "itinerary_days",
        ["offline_activity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_itinerary_days_online_activity_id"),
        "itinerary_days",
        ["online_activity_id"],
        unique=False,
    )
    op.drop_constraint(
        op.f("itinerary_days_trek_id_fkey"), "itinerary_days", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "itinerary_days", "treks", ["offline_activity_id"], ["id"]
    )
    op.create_foreign_key(
        None, "itinerary_days", "places", ["online_activity_id"], ["id"]
    )
    op.drop_column("itinerary_days", "trek_id")

    # Create the new enum type
    op.execute(
        "CREATE TYPE onlineactivitytypeenum AS ENUM ('HISTORICAL_SITE', 'TEMPLE', 'MUSEUM', 'PARK', 'ADVENTURE_SPORT', 'CULTURAL_SITE', 'RESTAURANT', 'SHOPPING', 'NIGHTLIFE')"
    )

    # Alter the column to use the new enum type
    op.execute(
        "ALTER TABLE places ALTER COLUMN place_type TYPE onlineactivitytypeenum USING place_type::text::onlineactivitytypeenum"
    )

    # Drop the old enum type
    op.execute("DROP TYPE IF EXISTS placetypeenum")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Create the old enum type
    op.execute(
        "CREATE TYPE placetypeenum AS ENUM ('HISTORICAL_SITE', 'TEMPLE', 'MUSEUM', 'PARK', 'ADVENTURE_SPORT', 'CULTURAL_SITE', 'RESTAURANT', 'SHOPPING', 'NIGHTLIFE')"
    )

    # Alter the column to use the old enum type
    op.execute(
        "ALTER TABLE places ALTER COLUMN place_type TYPE placetypeenum USING place_type::text::placetypeenum"
    )

    # Drop the new enum type
    op.execute("DROP TYPE IF EXISTS onlineactivitytypeenum")
    op.add_column(
        "itinerary_days",
        sa.Column("trek_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "itinerary_days", type_="foreignkey")
    op.drop_constraint(None, "itinerary_days", type_="foreignkey")
    op.create_foreign_key(
        op.f("itinerary_days_trek_id_fkey"),
        "itinerary_days",
        "treks",
        ["trek_id"],
        ["id"],
    )
    op.drop_index(
        op.f("ix_itinerary_days_online_activity_id"), table_name="itinerary_days"
    )
    op.drop_index(
        op.f("ix_itinerary_days_offline_activity_id"), table_name="itinerary_days"
    )
    op.create_index(
        op.f("ix_itinerary_days_trek_id"), "itinerary_days", ["trek_id"], unique=False
    )
    op.drop_column("itinerary_days", "online_activity_id")
    op.drop_column("itinerary_days", "offline_activity_id")
    op.create_table(
        "spatial_ref_sys",
        sa.Column("srid", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "auth_name", sa.VARCHAR(length=256), autoincrement=False, nullable=True
        ),
        sa.Column("auth_srid", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "srtext", sa.VARCHAR(length=2048), autoincrement=False, nullable=True
        ),
        sa.Column(
            "proj4text", sa.VARCHAR(length=2048), autoincrement=False, nullable=True
        ),
        sa.CheckConstraint(
            "srid > 0 AND srid <= 998999", name=op.f("spatial_ref_sys_srid_check")
        ),
        sa.PrimaryKeyConstraint("srid", name=op.f("spatial_ref_sys_pkey")),
    )
    # ### end Alembic commands ###
