"""add_trek_starting_coordinates

Revision ID: 78c82ca8793f
Revises: d0b38e0a3c94
Create Date: 2025-09-09 21:39:31.224225

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "78c82ca8793f"
down_revision: Union[str, Sequence[str], None] = "d0b38e0a3c94"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("treks", sa.Column("start_latitude", sa.Float(), nullable=True))
    op.add_column("treks", sa.Column("start_longitude", sa.Float(), nullable=True))
    op.create_index(
        op.f("ix_treks_start_latitude"), "treks", ["start_latitude"], unique=False
    )
    op.create_index(
        op.f("ix_treks_start_longitude"), "treks", ["start_longitude"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_treks_start_longitude"), table_name="treks")
    op.drop_index(op.f("ix_treks_start_latitude"), table_name="treks")
    op.drop_column("treks", "start_longitude")
    op.drop_column("treks", "start_latitude")
    # ### end Alembic commands ###
