"""Initial Migration

Revision ID: d0b38e0a3c94
Revises:
Create Date: 2025-09-09 21:12:42.830332

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = "d0b38e0a3c94"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_revoked", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_refresh_tokens_id"), "refresh_tokens", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_refresh_tokens_token"), "refresh_tokens", ["token"], unique=True
    )
    op.create_index(
        op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("middle_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("last_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("password_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("country_code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("phone_number", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("indian_citizenship", sa.Boolean(), nullable=False),
        sa.Column(
            "aadhar_number_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "passport_number_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "blockchain_address", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("tourist_id_token", sa.Integer(), nullable=True),
        sa.Column(
            "tourist_id_transaction_hash",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
        ),
        sa.Column("is_kyc_verified", sa.Boolean(), nullable=False),
        sa.Column("is_email_verified", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("ADMIN", "TOURIST", "GUIDE", "SUPER_ADMIN", name="userroleenum"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_users_country_code"), "users", ["country_code"], unique=False
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_first_name"), "users", ["first_name"], unique=False)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(
        op.f("ix_users_phone_number"), "users", ["phone_number"], unique=True
    )
    op.create_table(
        "guides",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("specialties", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("years_of_experience", sa.Integer(), nullable=True),
        sa.Column(
            "certification_level",
            sa.Enum(
                "BASIC",
                "INTERMEDIATE",
                "ADVANCED",
                "EXPERT",
                name="guidecertificationlevelenum",
            ),
            nullable=True,
        ),
        sa.Column(
            "certification_number", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "languages_spoken", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "preferred_trek_regions", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("max_group_size", sa.Integer(), nullable=True),
        sa.Column("daily_rate", sa.Float(), nullable=True),
        sa.Column("license_number", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("insurance_valid_until", sa.Date(), nullable=True),
        sa.Column(
            "emergency_contact_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "emergency_contact_phone", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("average_rating", sa.Float(), nullable=True),
        sa.Column("total_reviews", sa.Integer(), nullable=False),
        sa.Column("total_treks_completed", sa.Integer(), nullable=False),
        sa.Column("is_available", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("profile_completion_percentage", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_guides_id"), "guides", ["id"], unique=False)
    op.create_index(op.f("ix_guides_user_id"), "guides", ["user_id"], unique=True)
    op.create_table(
        "places",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "place_type",
            sa.Enum(
                "TREK",
                "CITY_TOUR",
                "HISTORICAL_SITE",
                "TEMPLE",
                "MUSEUM",
                "PARK",
                "BEACH",
                "HILL_STATION",
                "ADVENTURE_SPORT",
                "CULTURAL_SITE",
                "RESTAURANT",
                "SHOPPING",
                "NIGHTLIFE",
                "OTHER",
                name="placetypeenum",
            ),
            nullable=False,
        ),
        sa.Column("city", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("state", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("country", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("address", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("duration_hours", sa.Integer(), nullable=True),
        sa.Column("entry_fee", sa.Float(), nullable=True),
        sa.Column("best_season", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("wheelchair_accessible", sa.Boolean(), nullable=False),
        sa.Column("safety_rating", sa.Integer(), nullable=True),
        sa.Column("contact_number", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("website", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("opening_time", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("closing_time", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_featured", sa.Boolean(), nullable=False),
        sa.Column("created_by_admin_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_admin_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_places_city"), "places", ["city"], unique=False)
    op.create_index(op.f("ix_places_country"), "places", ["country"], unique=False)
    op.create_index(
        op.f("ix_places_created_at"), "places", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_places_created_by_admin_id"),
        "places",
        ["created_by_admin_id"],
        unique=False,
    )
    op.create_index(op.f("ix_places_id"), "places", ["id"], unique=False)
    op.create_index(op.f("ix_places_is_active"), "places", ["is_active"], unique=False)
    op.create_index(
        op.f("ix_places_is_featured"), "places", ["is_featured"], unique=False
    )
    op.create_index(op.f("ix_places_latitude"), "places", ["latitude"], unique=False)
    op.create_index(op.f("ix_places_longitude"), "places", ["longitude"], unique=False)
    op.create_index(op.f("ix_places_name"), "places", ["name"], unique=False)
    op.create_index(
        op.f("ix_places_place_type"), "places", ["place_type"], unique=False
    )
    op.create_index(op.f("ix_places_state"), "places", ["state"], unique=False)
    op.create_index(
        op.f("ix_places_updated_at"), "places", ["updated_at"], unique=False
    )
    op.create_table(
        "treks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("location", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("city", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("district", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("state", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("duration", sa.Integer(), nullable=False),
        sa.Column("altitude", sa.Integer(), nullable=True),
        sa.Column("nearest_town", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("best_season", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "permits_required", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "equipment_needed", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("safety_tips", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("minimum_age", sa.Integer(), nullable=True),
        sa.Column("maximum_age", sa.Integer(), nullable=True),
        sa.Column("guide_required", sa.Boolean(), nullable=False),
        sa.Column("minimum_people", sa.Integer(), nullable=True),
        sa.Column("maximum_people", sa.Integer(), nullable=True),
        sa.Column("cost_per_person", sa.Float(), nullable=True),
        sa.Column(
            "difficulty_level",
            sa.Enum("EASY", "MEDIUM", "HARD", name="difficultylevelenum"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_treks_altitude"), "treks", ["altitude"], unique=False)
    op.create_index(op.f("ix_treks_city"), "treks", ["city"], unique=False)
    op.create_index(
        op.f("ix_treks_cost_per_person"), "treks", ["cost_per_person"], unique=False
    )
    op.create_index(op.f("ix_treks_created_at"), "treks", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_treks_created_by_id"), "treks", ["created_by_id"], unique=False
    )
    op.create_index(
        op.f("ix_treks_difficulty_level"), "treks", ["difficulty_level"], unique=False
    )
    op.create_index(op.f("ix_treks_district"), "treks", ["district"], unique=False)
    op.create_index(op.f("ix_treks_duration"), "treks", ["duration"], unique=False)
    op.create_index(
        op.f("ix_treks_guide_required"), "treks", ["guide_required"], unique=False
    )
    op.create_index(op.f("ix_treks_id"), "treks", ["id"], unique=False)
    op.create_index(op.f("ix_treks_location"), "treks", ["location"], unique=False)
    op.create_index(
        op.f("ix_treks_maximum_age"), "treks", ["maximum_age"], unique=False
    )
    op.create_index(
        op.f("ix_treks_maximum_people"), "treks", ["maximum_people"], unique=False
    )
    op.create_index(
        op.f("ix_treks_minimum_age"), "treks", ["minimum_age"], unique=False
    )
    op.create_index(
        op.f("ix_treks_minimum_people"), "treks", ["minimum_people"], unique=False
    )
    op.create_index(op.f("ix_treks_name"), "treks", ["name"], unique=False)
    op.create_index(
        op.f("ix_treks_nearest_town"), "treks", ["nearest_town"], unique=False
    )
    op.create_index(op.f("ix_treks_state"), "treks", ["state"], unique=False)
    op.create_table(
        "guide_treks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("guide_id", sa.Integer(), nullable=False),
        sa.Column("trek_id", sa.Integer(), nullable=False),
        sa.Column("assigned_at", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["guide_id"],
            ["guides.id"],
        ),
        sa.ForeignKeyConstraint(
            ["trek_id"],
            ["treks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_guide_treks_assigned_at"), "guide_treks", ["assigned_at"], unique=False
    )
    op.create_index(
        op.f("ix_guide_treks_guide_id"), "guide_treks", ["guide_id"], unique=False
    )
    op.create_index(op.f("ix_guide_treks_id"), "guide_treks", ["id"], unique=False)
    op.create_index(
        op.f("ix_guide_treks_is_active"), "guide_treks", ["is_active"], unique=False
    )
    op.create_index(
        op.f("ix_guide_treks_trek_id"), "guide_treks", ["trek_id"], unique=False
    )
    op.create_table(
        "itineraries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "itinerary_type",
            sa.Enum("TREK", "CITY_TOUR", "MIXED", name="itinerarytypeenum"),
            nullable=False,
        ),
        sa.Column("trek_id", sa.Integer(), nullable=True),
        sa.Column("primary_place_id", sa.Integer(), nullable=True),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "destination_city", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "destination_state", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "destination_country", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("total_duration_days", sa.Integer(), nullable=False),
        sa.Column("estimated_budget", sa.Float(), nullable=True),
        sa.Column("number_of_travelers", sa.Integer(), nullable=False),
        sa.Column(
            "purpose_of_visit", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "SUBMITTED",
                "APPROVED",
                "ACTIVE",
                "COMPLETED",
                "CANCELLED",
                name="itinerarystatusenum",
            ),
            nullable=False,
        ),
        sa.Column(
            "emergency_contact_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "emergency_contact_phone",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
        ),
        sa.Column(
            "emergency_contact_relation",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
        ),
        sa.Column(
            "preferred_language", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "special_requirements", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.Column("approved_at", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["primary_place_id"],
            ["places.id"],
        ),
        sa.ForeignKeyConstraint(
            ["trek_id"],
            ["treks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_itineraries_created_at"), "itineraries", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_itineraries_destination_city"),
        "itineraries",
        ["destination_city"],
        unique=False,
    )
    op.create_index(
        op.f("ix_itineraries_destination_country"),
        "itineraries",
        ["destination_country"],
        unique=False,
    )
    op.create_index(
        op.f("ix_itineraries_destination_state"),
        "itineraries",
        ["destination_state"],
        unique=False,
    )
    op.create_index(
        op.f("ix_itineraries_end_date"), "itineraries", ["end_date"], unique=False
    )
    op.create_index(op.f("ix_itineraries_id"), "itineraries", ["id"], unique=False)
    op.create_index(
        op.f("ix_itineraries_itinerary_type"),
        "itineraries",
        ["itinerary_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_itineraries_primary_place_id"),
        "itineraries",
        ["primary_place_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_itineraries_start_date"), "itineraries", ["start_date"], unique=False
    )
    op.create_index(
        op.f("ix_itineraries_status"), "itineraries", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_itineraries_title"), "itineraries", ["title"], unique=False
    )
    op.create_index(
        op.f("ix_itineraries_total_duration_days"),
        "itineraries",
        ["total_duration_days"],
        unique=False,
    )
    op.create_index(
        op.f("ix_itineraries_trek_id"), "itineraries", ["trek_id"], unique=False
    )
    op.create_index(
        op.f("ix_itineraries_updated_at"), "itineraries", ["updated_at"], unique=False
    )
    op.create_index(
        op.f("ix_itineraries_user_id"), "itineraries", ["user_id"], unique=False
    )
    op.create_table(
        "tracking_devices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("device_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("api_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("treck_id", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE", "INACTIVE", "MAINTENANCE", name="trackingdevicestatusenum"
            ),
            nullable=False,
        ),
        sa.Column(
            "last_known_location", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("battery_level", sa.Float(), nullable=True),
        sa.Column("signal_strength", sa.Float(), nullable=True),
        sa.Column("activated_at", sa.Integer(), nullable=True),
        sa.Column("deactivated_at", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["treck_id"],
            ["treks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tracking_devices_api_key"),
        "tracking_devices",
        ["api_key"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tracking_devices_created_at"),
        "tracking_devices",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tracking_devices_device_id"),
        "tracking_devices",
        ["device_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_tracking_devices_id"), "tracking_devices", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_tracking_devices_status"), "tracking_devices", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_tracking_devices_treck_id"),
        "tracking_devices",
        ["treck_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tracking_devices_updated_at"),
        "tracking_devices",
        ["updated_at"],
        unique=False,
    )
    op.create_table(
        "trek_route_data",
        sa.Column("trek_id", sa.Integer(), nullable=False),
        sa.Column(
            "route",
            geoalchemy2.types.Geometry(
                geometry_type="LINESTRING",
                srid=4326,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["trek_id"],
            ["treks.id"],
        ),
        sa.PrimaryKeyConstraint("trek_id"),
    )
    # Use IF NOT EXISTS to prevent duplicate index error
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_trek_route_data_route ON trek_route_data USING gist (route)"
    )
    op.create_index(
        op.f("ix_trek_route_data_created_at"),
        "trek_route_data",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_trek_route_data_trek_id"), "trek_route_data", ["trek_id"], unique=False
    )
    op.create_index(
        op.f("ix_trek_route_data_updated_at"),
        "trek_route_data",
        ["updated_at"],
        unique=False,
    )
    op.create_table(
        "itinerary_days",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("itinerary_id", sa.Integer(), nullable=False),
        sa.Column("day_number", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column(
            "day_type",
            sa.Enum("TREK_DAY", "PLACE_VISIT_DAY", name="daytypeenum"),
            nullable=False,
        ),
        sa.Column("trek_id", sa.Integer(), nullable=True),
        sa.Column("primary_place_id", sa.Integer(), nullable=True),
        sa.Column(
            "planned_activities", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "estimated_time_start", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "estimated_time_end", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "accommodation_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "accommodation_type",
            sa.Enum(
                "HOTEL",
                "GUEST_HOUSE",
                "HOMESTAY",
                "CAMPING",
                "HOSTEL",
                "RESORT",
                "OTHER",
                name="accommodationtypeenum",
            ),
            nullable=True,
        ),
        sa.Column(
            "accommodation_address", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "accommodation_contact", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("accommodation_latitude", sa.Float(), nullable=True),
        sa.Column("accommodation_longitude", sa.Float(), nullable=True),
        sa.Column(
            "transport_mode",
            sa.Enum(
                "FLIGHT",
                "TRAIN",
                "BUS",
                "CAR",
                "TAXI",
                "WALKING",
                "OTHER",
                name="transportmodeenum",
            ),
            nullable=True,
        ),
        sa.Column(
            "transport_details", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("risk_level", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("safety_notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "special_instructions", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["itinerary_id"],
            ["itineraries.id"],
        ),
        sa.ForeignKeyConstraint(
            ["primary_place_id"],
            ["places.id"],
        ),
        sa.ForeignKeyConstraint(
            ["trek_id"],
            ["treks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_itinerary_days_created_at"),
        "itinerary_days",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_itinerary_days_date"), "itinerary_days", ["date"], unique=False
    )
    op.create_index(
        op.f("ix_itinerary_days_day_number"),
        "itinerary_days",
        ["day_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_itinerary_days_day_type"), "itinerary_days", ["day_type"], unique=False
    )
    op.create_index(
        op.f("ix_itinerary_days_id"), "itinerary_days", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_itinerary_days_itinerary_id"),
        "itinerary_days",
        ["itinerary_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_itinerary_days_primary_place_id"),
        "itinerary_days",
        ["primary_place_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_itinerary_days_trek_id"), "itinerary_days", ["trek_id"], unique=False
    )
    op.create_index(
        op.f("ix_itinerary_days_updated_at"),
        "itinerary_days",
        ["updated_at"],
        unique=False,
    )
    op.create_table(
        "trips",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("itinerary_id", sa.Integer(), nullable=True),
        sa.Column("trek_id", sa.Integer(), nullable=True),
        sa.Column("guide_id", sa.Integer(), nullable=True),
        sa.Column("tracking_deivce_id", sa.Integer(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "ASSIGNED",
                "IN_PROGRESS",
                "COMPLETED",
                "CANCELLED",
                name="tripstatusenum",
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["guide_id"],
            ["guides.id"],
        ),
        sa.ForeignKeyConstraint(
            ["itinerary_id"],
            ["itineraries.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tracking_deivce_id"],
            ["tracking_devices.id"],
        ),
        sa.ForeignKeyConstraint(
            ["trek_id"],
            ["treks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_trips_end_date"), "trips", ["end_date"], unique=False)
    op.create_index(op.f("ix_trips_guide_id"), "trips", ["guide_id"], unique=False)
    op.create_index(op.f("ix_trips_id"), "trips", ["id"], unique=False)
    op.create_index(
        op.f("ix_trips_itinerary_id"), "trips", ["itinerary_id"], unique=False
    )
    op.create_index(op.f("ix_trips_start_date"), "trips", ["start_date"], unique=False)
    op.create_index(op.f("ix_trips_status"), "trips", ["status"], unique=False)
    op.create_index(
        op.f("ix_trips_tracking_deivce_id"),
        "trips",
        ["tracking_deivce_id"],
        unique=False,
    )
    op.create_index(op.f("ix_trips_trek_id"), "trips", ["trek_id"], unique=False)
    op.create_index(op.f("ix_trips_user_id"), "trips", ["user_id"], unique=False)
    op.create_table(
        "alerts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("trip_id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.Integer(), nullable=False),
        sa.Column(
            "alert_type",
            sa.Enum("DEVIATION", "EMERGENCY", "WEATHER", "OTHER", name="alerttypeenum"),
            nullable=False,
        ),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "location",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.Enum("NEW", "ACKNOWLEDGED", "RESOLVED", name="alertstatusenum"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["trip_id"],
            ["trips.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # Use IF NOT EXISTS to prevent duplicate index error
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_alerts_location ON alerts USING gist (location)"
    )
    op.create_index(
        op.f("ix_alerts_alert_type"), "alerts", ["alert_type"], unique=False
    )
    op.create_index(op.f("ix_alerts_id"), "alerts", ["id"], unique=False)
    op.create_index(op.f("ix_alerts_status"), "alerts", ["status"], unique=False)
    op.create_index(op.f("ix_alerts_timestamp"), "alerts", ["timestamp"], unique=False)
    op.create_index(op.f("ix_alerts_trip_id"), "alerts", ["trip_id"], unique=False)
    op.create_table(
        "location_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("trip_id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.Integer(), nullable=False),
        sa.Column(
            "location",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["trip_id"],
            ["trips.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # Use IF NOT EXISTS to prevent duplicate index error
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_location_history_location ON location_history USING gist (location)"
    )
    op.create_index(
        op.f("ix_location_history_id"), "location_history", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_location_history_timestamp"),
        "location_history",
        ["timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_location_history_trip_id"),
        "location_history",
        ["trip_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_location_history_trip_id"), table_name="location_history")
    op.drop_index(op.f("ix_location_history_timestamp"), table_name="location_history")
    op.drop_index(op.f("ix_location_history_id"), table_name="location_history")
    # Use IF EXISTS to prevent errors if index doesn't exist
    op.execute("DROP INDEX IF EXISTS idx_location_history_location")
    op.drop_table("location_history")
    op.drop_index(op.f("ix_alerts_trip_id"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_timestamp"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_status"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_id"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_alert_type"), table_name="alerts")
    # Use IF EXISTS to prevent errors if index doesn't exist
    op.execute("DROP INDEX IF EXISTS idx_alerts_location")
    op.drop_table("alerts")
    op.drop_index(op.f("ix_trips_user_id"), table_name="trips")
    op.drop_index(op.f("ix_trips_trek_id"), table_name="trips")
    op.drop_index(op.f("ix_trips_tracking_deivce_id"), table_name="trips")
    op.drop_index(op.f("ix_trips_status"), table_name="trips")
    op.drop_index(op.f("ix_trips_start_date"), table_name="trips")
    op.drop_index(op.f("ix_trips_itinerary_id"), table_name="trips")
    op.drop_index(op.f("ix_trips_id"), table_name="trips")
    op.drop_index(op.f("ix_trips_guide_id"), table_name="trips")
    op.drop_index(op.f("ix_trips_end_date"), table_name="trips")
    op.drop_table("trips")
    op.drop_index(op.f("ix_itinerary_days_updated_at"), table_name="itinerary_days")
    op.drop_index(op.f("ix_itinerary_days_trek_id"), table_name="itinerary_days")
    op.drop_index(
        op.f("ix_itinerary_days_primary_place_id"), table_name="itinerary_days"
    )
    op.drop_index(op.f("ix_itinerary_days_itinerary_id"), table_name="itinerary_days")
    op.drop_index(op.f("ix_itinerary_days_id"), table_name="itinerary_days")
    op.drop_index(op.f("ix_itinerary_days_day_type"), table_name="itinerary_days")
    op.drop_index(op.f("ix_itinerary_days_day_number"), table_name="itinerary_days")
    op.drop_index(op.f("ix_itinerary_days_date"), table_name="itinerary_days")
    op.drop_index(op.f("ix_itinerary_days_created_at"), table_name="itinerary_days")
    op.drop_table("itinerary_days")
    op.drop_index(op.f("ix_trek_route_data_updated_at"), table_name="trek_route_data")
    op.drop_index(op.f("ix_trek_route_data_trek_id"), table_name="trek_route_data")
    op.drop_index(op.f("ix_trek_route_data_created_at"), table_name="trek_route_data")
    # Use IF EXISTS to prevent errors if index doesn't exist
    op.execute("DROP INDEX IF EXISTS idx_trek_route_data_route")
    op.drop_table("trek_route_data")
    op.drop_index(op.f("ix_tracking_devices_updated_at"), table_name="tracking_devices")
    op.drop_index(op.f("ix_tracking_devices_treck_id"), table_name="tracking_devices")
    op.drop_index(op.f("ix_tracking_devices_status"), table_name="tracking_devices")
    op.drop_index(op.f("ix_tracking_devices_id"), table_name="tracking_devices")
    op.drop_index(op.f("ix_tracking_devices_device_id"), table_name="tracking_devices")
    op.drop_index(op.f("ix_tracking_devices_created_at"), table_name="tracking_devices")
    op.drop_index(op.f("ix_tracking_devices_api_key"), table_name="tracking_devices")
    op.drop_table("tracking_devices")
    op.drop_index(op.f("ix_itineraries_user_id"), table_name="itineraries")
    op.drop_index(op.f("ix_itineraries_updated_at"), table_name="itineraries")
    op.drop_index(op.f("ix_itineraries_trek_id"), table_name="itineraries")
    op.drop_index(op.f("ix_itineraries_total_duration_days"), table_name="itineraries")
    op.drop_index(op.f("ix_itineraries_title"), table_name="itineraries")
    op.drop_index(op.f("ix_itineraries_status"), table_name="itineraries")
    op.drop_index(op.f("ix_itineraries_start_date"), table_name="itineraries")
    op.drop_index(op.f("ix_itineraries_primary_place_id"), table_name="itineraries")
    op.drop_index(op.f("ix_itineraries_itinerary_type"), table_name="itineraries")
    op.drop_index(op.f("ix_itineraries_id"), table_name="itineraries")
    op.drop_index(op.f("ix_itineraries_end_date"), table_name="itineraries")
    op.drop_index(op.f("ix_itineraries_destination_state"), table_name="itineraries")
    op.drop_index(op.f("ix_itineraries_destination_country"), table_name="itineraries")
    op.drop_index(op.f("ix_itineraries_destination_city"), table_name="itineraries")
    op.drop_index(op.f("ix_itineraries_created_at"), table_name="itineraries")
    op.drop_table("itineraries")
    op.drop_index(op.f("ix_guide_treks_trek_id"), table_name="guide_treks")
    op.drop_index(op.f("ix_guide_treks_is_active"), table_name="guide_treks")
    op.drop_index(op.f("ix_guide_treks_id"), table_name="guide_treks")
    op.drop_index(op.f("ix_guide_treks_guide_id"), table_name="guide_treks")
    op.drop_index(op.f("ix_guide_treks_assigned_at"), table_name="guide_treks")
    op.drop_table("guide_treks")
    op.drop_index(op.f("ix_treks_state"), table_name="treks")
    op.drop_index(op.f("ix_treks_nearest_town"), table_name="treks")
    op.drop_index(op.f("ix_treks_name"), table_name="treks")
    op.drop_index(op.f("ix_treks_minimum_people"), table_name="treks")
    op.drop_index(op.f("ix_treks_minimum_age"), table_name="treks")
    op.drop_index(op.f("ix_treks_maximum_people"), table_name="treks")
    op.drop_index(op.f("ix_treks_maximum_age"), table_name="treks")
    op.drop_index(op.f("ix_treks_location"), table_name="treks")
    op.drop_index(op.f("ix_treks_id"), table_name="treks")
    op.drop_index(op.f("ix_treks_guide_required"), table_name="treks")
    op.drop_index(op.f("ix_treks_duration"), table_name="treks")
    op.drop_index(op.f("ix_treks_district"), table_name="treks")
    op.drop_index(op.f("ix_treks_difficulty_level"), table_name="treks")
    op.drop_index(op.f("ix_treks_created_by_id"), table_name="treks")
    op.drop_index(op.f("ix_treks_created_at"), table_name="treks")
    op.drop_index(op.f("ix_treks_cost_per_person"), table_name="treks")
    op.drop_index(op.f("ix_treks_city"), table_name="treks")
    op.drop_index(op.f("ix_treks_altitude"), table_name="treks")
    op.drop_table("treks")
    op.drop_index(op.f("ix_places_updated_at"), table_name="places")
    op.drop_index(op.f("ix_places_state"), table_name="places")
    op.drop_index(op.f("ix_places_place_type"), table_name="places")
    op.drop_index(op.f("ix_places_name"), table_name="places")
    op.drop_index(op.f("ix_places_longitude"), table_name="places")
    op.drop_index(op.f("ix_places_latitude"), table_name="places")
    op.drop_index(op.f("ix_places_is_featured"), table_name="places")
    op.drop_index(op.f("ix_places_is_active"), table_name="places")
    op.drop_index(op.f("ix_places_id"), table_name="places")
    op.drop_index(op.f("ix_places_created_by_admin_id"), table_name="places")
    op.drop_index(op.f("ix_places_created_at"), table_name="places")
    op.drop_index(op.f("ix_places_country"), table_name="places")
    op.drop_index(op.f("ix_places_city"), table_name="places")
    op.drop_table("places")
    op.drop_index(op.f("ix_guides_user_id"), table_name="guides")
    op.drop_index(op.f("ix_guides_id"), table_name="guides")
    op.drop_table("guides")
    op.drop_index(op.f("ix_users_phone_number"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_first_name"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_country_code"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_token"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_id"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    # ### end Alembic commands ###
