"""add_itinerary_tables

Revision ID: da42523010d0
Revises: 6c31bc01f9d2
Create Date: 2025-09-09 02:14:00.893581

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "da42523010d0"
down_revision: Union[str, Sequence[str], None] = "6c31bc01f9d2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("trips", sa.Column("itinerary_id", sa.Integer(), nullable=True))
    op.create_index(
        op.f("ix_trips_itinerary_id"), "trips", ["itinerary_id"], unique=False
    )
    op.create_foreign_key(None, "trips", "itineraries", ["itinerary_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "trips", type_="foreignkey")
    op.drop_index(op.f("ix_trips_itinerary_id"), table_name="trips")
    op.drop_column("trips", "itinerary_id")
    op.create_table(
        "spatial_ref_sys",
        sa.Column("srid", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "auth_name", sa.VARCHAR(length=256), autoincrement=False, nullable=True
        ),
        sa.Column("auth_srid", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "srtext", sa.VARCHAR(length=2048), autoincrement=False, nullable=True
        ),
        sa.Column(
            "proj4text", sa.VARCHAR(length=2048), autoincrement=False, nullable=True
        ),
        sa.CheckConstraint(
            "srid > 0 AND srid <= 998999", name=op.f("spatial_ref_sys_srid_check")
        ),
        sa.PrimaryKeyConstraint("srid", name=op.f("spatial_ref_sys_pkey")),
    )
    # ### end Alembic commands ###
