"""add_itinerary_tables

Revision ID: da42523010d0
Revises: 6c31bc01f9d2
Create Date: 2025-09-09 02:14:00.893581

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "da42523010d0"
down_revision: Union[str, Sequence[str], None] = "6c31bc01f9d2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Create itineraries table first
    op.create_table(
        "itineraries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("trek_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("total_duration_days", sa.Integer(), nullable=False),
        sa.Column("estimated_budget", sa.Float(), nullable=True),
        sa.Column("number_of_travelers", sa.Integer(), nullable=False),
        sa.Column("purpose_of_visit", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("emergency_contact_name", sa.String(), nullable=False),
        sa.Column("emergency_contact_phone", sa.String(), nullable=False),
        sa.Column("emergency_contact_relation", sa.String(), nullable=False),
        sa.Column("preferred_language", sa.String(), nullable=True),
        sa.Column("special_requirements", sa.String(), nullable=True),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.Column("submitted_at", sa.Integer(), nullable=True),
        sa.Column("approved_at", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.ForeignKeyConstraint(["trek_id"], ["treks.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_itineraries_id"), "itineraries", ["id"], unique=False)
    op.create_index(
        op.f("ix_itineraries_user_id"), "itineraries", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_itineraries_trek_id"), "itineraries", ["trek_id"], unique=False
    )
    op.create_index(
        op.f("ix_itineraries_title"), "itineraries", ["title"], unique=False
    )
    op.create_index(
        op.f("ix_itineraries_start_date"), "itineraries", ["start_date"], unique=False
    )
    op.create_index(
        op.f("ix_itineraries_end_date"), "itineraries", ["end_date"], unique=False
    )
    op.create_index(
        op.f("ix_itineraries_total_duration_days"),
        "itineraries",
        ["total_duration_days"],
        unique=False,
    )
    op.create_index(
        op.f("ix_itineraries_status"), "itineraries", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_itineraries_created_at"), "itineraries", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_itineraries_updated_at"), "itineraries", ["updated_at"], unique=False
    )

    # Create itinerary_days table
    op.create_table(
        "itinerary_days",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("itinerary_id", sa.Integer(), nullable=False),
        sa.Column("day_number", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("planned_activities", sa.String(), nullable=False),
        sa.Column("estimated_time_start", sa.String(), nullable=True),
        sa.Column("estimated_time_end", sa.String(), nullable=True),
        sa.Column("accommodation_name", sa.String(), nullable=True),
        sa.Column("accommodation_type", sa.String(), nullable=True),
        sa.Column("accommodation_address", sa.String(), nullable=True),
        sa.Column("accommodation_contact", sa.String(), nullable=True),
        sa.Column("transport_mode", sa.String(), nullable=True),
        sa.Column("transport_details", sa.String(), nullable=True),
        sa.Column("risk_level", sa.String(), nullable=False),
        sa.Column("safety_notes", sa.String(), nullable=True),
        sa.Column("special_instructions", sa.String(), nullable=True),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["itinerary_id"], ["itineraries.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_itinerary_days_id"), "itinerary_days", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_itinerary_days_itinerary_id"),
        "itinerary_days",
        ["itinerary_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_itinerary_days_day_number"),
        "itinerary_days",
        ["day_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_itinerary_days_date"), "itinerary_days", ["date"], unique=False
    )
    op.create_index(
        op.f("ix_itinerary_days_created_at"),
        "itinerary_days",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_itinerary_days_updated_at"),
        "itinerary_days",
        ["updated_at"],
        unique=False,
    )

    # Now add the foreign key column to trips table
    op.add_column("trips", sa.Column("itinerary_id", sa.Integer(), nullable=True))
    op.create_index(
        op.f("ix_trips_itinerary_id"), "trips", ["itinerary_id"], unique=False
    )
    op.create_foreign_key(None, "trips", "itineraries", ["itinerary_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop foreign key from trips table first
    op.drop_constraint(None, "trips", type_="foreignkey")
    op.drop_index(op.f("ix_trips_itinerary_id"), table_name="trips")
    op.drop_column("trips", "itinerary_id")

    # Drop itinerary_days table (which references itineraries)
    op.drop_index(op.f("ix_itinerary_days_updated_at"), table_name="itinerary_days")
    op.drop_index(op.f("ix_itinerary_days_created_at"), table_name="itinerary_days")
    op.drop_index(op.f("ix_itinerary_days_date"), table_name="itinerary_days")
    op.drop_index(op.f("ix_itinerary_days_day_number"), table_name="itinerary_days")
    op.drop_index(op.f("ix_itinerary_days_itinerary_id"), table_name="itinerary_days")
    op.drop_index(op.f("ix_itinerary_days_id"), table_name="itinerary_days")
    op.drop_table("itinerary_days")

    # Drop itineraries table
    op.drop_index(op.f("ix_itineraries_updated_at"), table_name="itineraries")
    op.drop_index(op.f("ix_itineraries_created_at"), table_name="itineraries")
    op.drop_index(op.f("ix_itineraries_status"), table_name="itineraries")
    op.drop_index(op.f("ix_itineraries_total_duration_days"), table_name="itineraries")
    op.drop_index(op.f("ix_itineraries_end_date"), table_name="itineraries")
    op.drop_index(op.f("ix_itineraries_start_date"), table_name="itineraries")
    op.drop_index(op.f("ix_itineraries_title"), table_name="itineraries")
    op.drop_index(op.f("ix_itineraries_trek_id"), table_name="itineraries")
    op.drop_index(op.f("ix_itineraries_user_id"), table_name="itineraries")
    op.drop_index(op.f("ix_itineraries_id"), table_name="itineraries")
    op.drop_table("itineraries")

    op.create_table(
        "spatial_ref_sys",
        sa.Column("srid", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "auth_name", sa.VARCHAR(length=256), autoincrement=False, nullable=True
        ),
        sa.Column("auth_srid", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "srtext", sa.VARCHAR(length=2048), autoincrement=False, nullable=True
        ),
        sa.Column(
            "proj4text", sa.VARCHAR(length=2048), autoincrement=False, nullable=True
        ),
        sa.CheckConstraint(
            "srid > 0 AND srid <= 998999", name=op.f("spatial_ref_sys_srid_check")
        ),
        sa.PrimaryKeyConstraint("srid", name=op.f("spatial_ref_sys_pkey")),
    )
    # ### end Alembic commands ###
