"""update_itinerary_structure_with_trek_link

Revision ID: dae22fdf0f44
Revises: da42523010d0
Create Date: 2025-09-09 02:30:52.029411

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "dae22fdf0f44"
down_revision: Union[str, Sequence[str], None] = "da42523010d0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Trek_id column should already exist from the previous migration, no changes needed
    # The itineraries table was created with trek_id in the previous migration
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # No changes were made in upgrade, so no rollback needed
    pass
    # ### end Alembic commands ###
