"""update_itinerary_structure_with_trek_link

Revision ID: dae22fdf0f44
Revises: da42523010d0
Create Date: 2025-09-09 02:30:52.029411

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dae22fdf0f44"
down_revision: Union[str, Sequence[str], None] = "da42523010d0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add trek_id column to itineraries table (temporarily nullable for migration)
    op.add_column("itineraries", sa.Column("trek_id", sa.Integer(), nullable=True))
    op.drop_index(op.f("ix_itineraries_destination_city"), table_name="itineraries")
    op.drop_index(op.f("ix_itineraries_destination_district"), table_name="itineraries")
    op.drop_index(op.f("ix_itineraries_destination_state"), table_name="itineraries")
    op.create_index(
        op.f("ix_itineraries_trek_id"), "itineraries", ["trek_id"], unique=False
    )
    op.create_foreign_key(None, "itineraries", "treks", ["trek_id"], ["id"])
    op.drop_column("itineraries", "destination_district")
    op.drop_column("itineraries", "destination_state")
    op.drop_column("itineraries", "destination_city")
    op.drop_column("itinerary_days", "location_name")
    op.drop_column("itinerary_days", "longitude")
    op.drop_column("itinerary_days", "location_address")
    op.drop_column("itinerary_days", "latitude")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "itinerary_days",
        sa.Column(
            "latitude",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "itinerary_days",
        sa.Column("location_address", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "itinerary_days",
        sa.Column(
            "longitude",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "itinerary_days",
        sa.Column("location_name", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "itineraries",
        sa.Column(
            "destination_city", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "itineraries",
        sa.Column(
            "destination_state", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "itineraries",
        sa.Column(
            "destination_district", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(None, "itineraries", type_="foreignkey")
    op.drop_index(op.f("ix_itineraries_trek_id"), table_name="itineraries")
    op.create_index(
        op.f("ix_itineraries_destination_state"),
        "itineraries",
        ["destination_state"],
        unique=False,
    )
    op.create_index(
        op.f("ix_itineraries_destination_district"),
        "itineraries",
        ["destination_district"],
        unique=False,
    )
    op.create_index(
        op.f("ix_itineraries_destination_city"),
        "itineraries",
        ["destination_city"],
        unique=False,
    )
    op.drop_column("itineraries", "trek_id")
    op.create_table(
        "spatial_ref_sys",
        sa.Column("srid", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "auth_name", sa.VARCHAR(length=256), autoincrement=False, nullable=True
        ),
        sa.Column("auth_srid", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "srtext", sa.VARCHAR(length=2048), autoincrement=False, nullable=True
        ),
        sa.Column(
            "proj4text", sa.VARCHAR(length=2048), autoincrement=False, nullable=True
        ),
        sa.CheckConstraint(
            "srid > 0 AND srid <= 998999", name=op.f("spatial_ref_sys_srid_check")
        ),
        sa.PrimaryKeyConstraint("srid", name=op.f("spatial_ref_sys_pkey")),
    )
    # ### end Alembic commands ###
