"""add_location_sharing_table

Revision ID: f487adc32c07
Revises: 319d120eecc2
Create Date: 2025-09-11 23:07:44.634900

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f487adc32c07"
down_revision: Union[str, Sequence[str], None] = "319d120eecc2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Create location_share_history table
    op.create_table(
        "location_share_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("location_accuracy", sa.Float(), nullable=True),
        sa.Column("shared_with_contacts", sa.String(), nullable=False),
        sa.Column("message", sa.String(), nullable=False),
        sa.Column("emergency_level", sa.String(), nullable=False),
        sa.Column("trip_id", sa.Integer(), nullable=True),
        sa.Column("trip_info", sa.String(), nullable=True),
        sa.Column("share_method", sa.String(), nullable=False),
        sa.Column("device_info", sa.String(), nullable=True),
        sa.Column("timestamp", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("delivery_status", sa.String(), nullable=False),
        sa.Column("delivery_attempts", sa.Integer(), nullable=False),
        sa.Column("last_delivery_attempt", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )

    # Create indexes for location sharing table
    op.create_index(
        op.f("ix_location_share_history_id"),
        "location_share_history",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_location_share_history_user_id"),
        "location_share_history",
        ["user_id"],
        unique=False,
    )

    # Drop problematic spatial table if it exists
    try:
        op.drop_table("spatial_ref_sys")
    except Exception:
        pass

    # Drop alert indexes that might be causing issues
    try:
        op.drop_index(
            op.f("idx_alerts_emergency"),
            table_name="alerts",
            postgresql_where="(alert_type = 'EMERGENCY'::alerttypeenum)",
        )
    except Exception:
        pass
    try:
        op.drop_index(op.f("idx_alerts_status"), table_name="alerts")
    except Exception:
        pass
    try:
        op.drop_index(op.f("idx_alerts_timestamp"), table_name="alerts")
    except Exception:
        pass
    try:
        op.drop_index(op.f("idx_alerts_trip_id"), table_name="alerts")
    except Exception:
        pass
    try:
        op.drop_index(op.f("idx_alerts_trip_status"), table_name="alerts")
    except Exception:
        pass
    try:
        op.drop_index(op.f("idx_alerts_type"), table_name="alerts")
    except Exception:
        pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop location sharing table and indexes
    op.drop_index(
        op.f("ix_location_share_history_user_id"), table_name="location_share_history"
    )
    op.drop_index(
        op.f("ix_location_share_history_id"), table_name="location_share_history"
    )
    op.drop_table("location_share_history")

    # Recreate alert indexes
    try:
        op.create_index(op.f("idx_alerts_type"), "alerts", ["alert_type"], unique=False)
    except Exception:
        pass
    try:
        op.create_index(
            op.f("idx_alerts_trip_status"),
            "alerts",
            ["trip_id", "status", sa.literal_column("timestamp DESC")],
            unique=False,
        )
    except Exception:
        pass
    try:
        op.create_index(op.f("idx_alerts_trip_id"), "alerts", ["trip_id"], unique=False)
    except Exception:
        pass
    try:
        op.create_index(
            op.f("idx_alerts_timestamp"), "alerts", ["timestamp"], unique=False
        )
    except Exception:
        pass
    try:
        op.create_index(op.f("idx_alerts_status"), "alerts", ["status"], unique=False)
    except Exception:
        pass
    try:
        op.create_index(
            op.f("idx_alerts_emergency"),
            "alerts",
            ["alert_type", "status"],
            unique=False,
            postgresql_where="(alert_type = 'EMERGENCY'::alerttypeenum)",
        )
    except Exception:
        pass

    # Recreate spatial table if needed
    try:
        op.create_table(
            "spatial_ref_sys",
            sa.Column("srid", sa.INTEGER(), autoincrement=False, nullable=False),
            sa.Column(
                "auth_name", sa.VARCHAR(length=256), autoincrement=False, nullable=True
            ),
            sa.Column("auth_srid", sa.INTEGER(), autoincrement=False, nullable=True),
            sa.Column(
                "srtext", sa.VARCHAR(length=2048), autoincrement=False, nullable=True
            ),
            sa.Column(
                "proj4text", sa.VARCHAR(length=2048), autoincrement=False, nullable=True
            ),
            sa.CheckConstraint(
                "srid > 0 AND srid <= 998999", name=op.f("spatial_ref_sys_srid_check")
            ),
            sa.PrimaryKeyConstraint("srid", name=op.f("spatial_ref_sys_pkey")),
        )
    except Exception:
        pass
    # ### end Alembic commands ###
